// 熟語の例文データ: { "熟語": [英語例文, 日本語訳] }
const EXAMPLES = {
  // ===== 句動詞 =====
  "get up": ["I get up at six every morning.", "私は毎朝6時に起きる。"],
  "get along with": ["I get along with my coworkers.", "私は同僚とうまくやっている。"],
  "get over": ["It took me a week to get over my cold.", "風邪が治るのに1週間かかった。"],
  "get rid of": ["I want to get rid of these old clothes.", "この古い服を処分したい。"],
  "get back": ["What time did you get back home?", "何時に家に戻ったの？"],
  "get in": ["Get in the car. We are leaving.", "車に乗って。出発するよ。"],
  "get out": ["Let's get out of here.", "ここから出よう。"],
  "get off": ["I get off the train at the next station.", "次の駅で電車を降ります。"],
  "get on": ["She got on the bus at the last stop.", "彼女は終点の一つ前でバスに乗った。"],
  "get through": ["We got through a difficult year.", "私たちは大変な1年を乗り切った。"],
  "get together": ["Let's get together this weekend.", "今週末集まろうよ。"],
  "get away": ["I need to get away for a few days.", "数日どこかへ逃避したい。"],
  "get by": ["We can get by on a small budget.", "少ない予算でもなんとかやっていける。"],
  "get into": ["I got into K-pop recently.", "最近K-POPにはまった。"],
  "get used to": ["You will get used to the new job soon.", "新しい仕事にはすぐ慣れるよ。"],
  "get in touch": ["Please get in touch with me anytime.", "いつでも連絡してください。"],
  "give up": ["Don't give up on your dream.", "夢をあきらめないで。"],
  "give back": ["Can you give back my pen?", "ペンを返してくれる？"],
  "give away": ["She gave away all her old books.", "彼女は古い本を全部あげてしまった。"],
  "give in": ["He finally gave in to his kids.", "彼はついに子どもたちに折れた。"],
  "go on": ["What is going on here?", "ここで何が起きているの？"],
  "go out": ["Do you want to go out for dinner?", "夕食に出かけない？"],
  "go over": ["Let's go over the plan again.", "計画をもう一度確認しよう。"],
  "go through": ["She went through a hard time.", "彼女はつらい時期を経験した。"],
  "go ahead": ["Go ahead, I'm listening.", "どうぞ、聞いているよ。"],
  "go off": ["My alarm went off at five.", "アラームが5時に鳴った。"],
  "come up": ["Something urgent came up at work.", "仕事で急な用件が持ち上がった。"],
  "come up with": ["He came up with a great idea.", "彼は素晴らしいアイデアを思いついた。"],
  "come across": ["I came across an old photo yesterday.", "昨日古い写真を偶然見つけた。"],
  "come over": ["Come over to my place tonight.", "今夜うちに遊びに来てよ。"],
  "come out": ["Her new book comes out next month.", "彼女の新しい本は来月出る。"],
  "come down with": ["I came down with the flu.", "インフルエンザにかかった。"],
  "take off": ["The plane takes off at noon.", "飛行機は正午に離陸する。"],
  "take on": ["I can't take on any more work.", "これ以上仕事を引き受けられない。"],
  "take over": ["She will take over the family business.", "彼女が家業を継ぐ。"],
  "take out": ["Can you take out the trash?", "ゴミを出してくれる？"],
  "take up": ["I took up tennis last year.", "去年テニスを始めた。"],
  "take care of": ["I take care of my little sister.", "私は妹の世話をしている。"],
  "take after": ["He takes after his father.", "彼は父親に似ている。"],
  "take place": ["The festival takes place in August.", "祭りは8月に行われる。"],
  "put on": ["Put on your jacket. It's cold.", "上着を着なさい。寒いよ。"],
  "put off": ["Don't put off your homework.", "宿題を先延ばしにしないで。"],
  "put up with": ["I can't put up with this noise.", "この騒音には我慢できない。"],
  "put away": ["Put away your toys, please.", "おもちゃを片付けてね。"],
  "put out": ["Firefighters put out the fire quickly.", "消防士たちはすぐに火を消した。"],
  "put down": ["Put down your phone during dinner.", "夕食中はスマホを置きなさい。"],
  "put together": ["We put together this desk ourselves.", "この机は自分たちで組み立てた。"],
  "look for": ["I'm looking for my keys.", "鍵を探しているんだ。"],
  "look after": ["Can you look after my dog this weekend?", "今週末うちの犬の面倒を見てくれる？"],
  "look forward to": ["I look forward to seeing you.", "お会いできるのを楽しみにしています。"],
  "look up": ["Look up the word in a dictionary.", "その単語を辞書で調べなさい。"],
  "look into": ["The police are looking into the case.", "警察がその事件を調査している。"],
  "look out": ["Look out! A car is coming.", "危ない！車が来てるよ。"],
  "look over": ["Please look over my report.", "私のレポートに目を通してください。"],
  "look up to": ["I look up to my grandmother.", "私は祖母を尊敬している。"],
  "look down on": ["Don't look down on others.", "他人を見下してはいけない。"],
  "turn on": ["Turn on the light, please.", "電気をつけてください。"],
  "turn off": ["Turn off the TV before bed.", "寝る前にテレビを消して。"],
  "turn up": ["He turned up an hour late.", "彼は1時間遅れて現れた。"],
  "turn down": ["She turned down the job offer.", "彼女はその仕事の誘いを断った。"],
  "turn out": ["The party turned out great.", "パーティーは結局大成功だった。"],
  "turn around": ["Turn around and look at me.", "振り向いて私を見て。"],
  "turn in": ["Turn in your homework by Friday.", "金曜までに宿題を提出しなさい。"],
  "run out of": ["We ran out of milk.", "牛乳を切らしてしまった。"],
  "run into": ["I ran into an old friend at the store.", "店で旧友に偶然会った。"],
  "run away": ["The cat ran away from home.", "猫が家出した。"],
  "run errands": ["I have to run errands this afternoon.", "今日の午後は用事を済ませないと。"],
  "break down": ["My car broke down on the highway.", "高速道路で車が故障した。"],
  "break up": ["They broke up last month.", "彼らは先月別れた。"],
  "break into": ["Someone broke into our house.", "誰かが家に押し入った。"],
  "break out": ["A fire broke out in the building.", "そのビルで火事が発生した。"],
  "bring up": ["She was brought up in Osaka.", "彼女は大阪で育った。"],
  "bring back": ["This song brings back memories.", "この曲は思い出をよみがえらせる。"],
  "bring about": ["The internet brought about big changes.", "インターネットは大きな変化をもたらした。"],
  "call off": ["They called off the game because of rain.", "雨で試合は中止になった。"],
  "call back": ["I'll call you back in ten minutes.", "10分後にかけ直すね。"],
  "carry on": ["Carry on with your work.", "仕事を続けてください。"],
  "carry out": ["We carried out the plan successfully.", "私たちは計画をうまく実行した。"],
  "catch up with": ["Run fast and catch up with them.", "速く走って彼らに追いつこう。"],
  "check in": ["We checked in at the hotel at three.", "3時にホテルにチェックインした。"],
  "check out": ["Check out this new cafe.", "この新しいカフェを見てみてよ。"],
  "cheer up": ["Cheer up! Tomorrow is another day.", "元気出して！明日があるさ。"],
  "clean up": ["Let's clean up the kitchen together.", "一緒に台所を片付けよう。"],
  "count on": ["You can count on me.", "私に任せて。"],
  "cut down on": ["I'm cutting down on sugar.", "砂糖を控えているんだ。"],
  "cut off": ["Our call was suddenly cut off.", "電話が突然切れた。"],
  "deal with": ["I'll deal with this problem.", "この問題は私が対処します。"],
  "drop by": ["Drop by my office anytime.", "いつでも私のオフィスに寄ってね。"],
  "drop off": ["I'll drop you off at the station.", "駅まで送っていくよ。"],
  "drop out": ["He dropped out of college.", "彼は大学を中退した。"],
  "end up": ["We ended up staying home.", "結局家にいることになった。"],
  "figure out": ["I can't figure out this math problem.", "この数学の問題が解けない。"],
  "fill out": ["Please fill out this form.", "この用紙に記入してください。"],
  "find out": ["I found out the truth.", "真実を知った。"],
  "fit in": ["She quickly fit in at her new school.", "彼女は新しい学校にすぐなじんだ。"],
  "focus on": ["Focus on your studies now.", "今は勉強に集中しなさい。"],
  "grow up": ["I grew up in a small town.", "私は小さな町で育った。"],
  "hand in": ["Hand in your paper by noon.", "正午までにレポートを提出してください。"],
  "hand out": ["The teacher handed out the tests.", "先生がテスト用紙を配った。"],
  "hang on": ["Hang on a second.", "ちょっと待って。"],
  "hang out": ["We hung out at the mall.", "私たちはモールで遊んだ。"],
  "hang up": ["Don't hang up yet.", "まだ電話を切らないで。"],
  "hold on": ["Hold on, I'll check.", "待って、確認するね。"],
  "keep up with": ["It's hard to keep up with the news.", "ニュースについていくのは大変だ。"],
  "keep on": ["Keep on trying.", "挑戦し続けなさい。"],
  "keep in mind": ["Keep in mind that time is limited.", "時間は限られていることを覚えておいて。"],
  "let down": ["I won't let you down.", "君をがっかりさせないよ。"],
  "make up": ["They fought but soon made up.", "彼らはけんかしたがすぐ仲直りした。"],
  "make up for": ["I'll make up for lost time.", "失った時間を埋め合わせるよ。"],
  "make out": ["I can't make out what the sign says.", "看板に何と書いてあるか読み取れない。"],
  "move on": ["It's time to move on.", "前に進むときだ。"],
  "pass away": ["My grandfather passed away last year.", "祖父は昨年亡くなった。"],
  "pass out": ["He almost passed out from the heat.", "彼は暑さで気を失いそうになった。"],
  "pay back": ["I'll pay you back tomorrow.", "明日お金を返すね。"],
  "pick up": ["I'll pick you up at seven.", "7時に車で迎えに行くよ。"],
  "point out": ["She pointed out my mistake.", "彼女は私の間違いを指摘した。"],
  "pull over": ["The police told him to pull over.", "警察は彼に車を停めるよう言った。"],
  "set up": ["They set up a new company.", "彼らは新しい会社を設立した。"],
  "settle down": ["He wants to settle down in the countryside.", "彼は田舎に落ち着きたいと思っている。"],
  "show up": ["She didn't show up for the meeting.", "彼女は会議に現れなかった。"],
  "show off": ["He likes to show off his new car.", "彼は新車を見せびらかすのが好きだ。"],
  "sign up": ["I signed up for a cooking class.", "料理教室に申し込んだ。"],
  "slow down": ["Slow down, you're driving too fast.", "スピードを落として、飛ばしすぎだよ。"],
  "sort out": ["Let's sort out this problem first.", "まずこの問題を解決しよう。"],
  "stand for": ["What does UN stand for?", "UNは何の略ですか？"],
  "stand out": ["Her red dress really stands out.", "彼女の赤いドレスはとても目立つ。"],
  "stay up": ["I stayed up late watching a movie.", "映画を見て夜更かしした。"],
  "stick to": ["Stick to your plan.", "自分の計画を貫きなさい。"],
  "think over": ["Let me think it over tonight.", "今夜じっくり考えさせて。"],
  "throw away": ["Don't throw away that box.", "その箱を捨てないで。"],
  "try on": ["Can I try on this jacket?", "このジャケットを試着してもいいですか？"],
  "try out": ["I want to try out the new app.", "新しいアプリを試してみたい。"],
  "wake up": ["I wake up at seven on weekdays.", "平日は7時に目が覚める。"],
  "warm up": ["Warm up before you run.", "走る前に準備運動をして。"],
  "watch out": ["Watch out for cars.", "車に気をつけて。"],
  "work out": ["I work out at the gym twice a week.", "週2回ジムで運動している。"],
  "write down": ["Write down your phone number here.", "ここに電話番号を書いてください。"],
  "back up": ["Back up your files regularly.", "ファイルはこまめにバックアップして。"],
  "blow up": ["He blew up when he heard the news.", "その知らせを聞いて彼は激怒した。"],
  "calm down": ["Calm down and tell me what happened.", "落ち着いて何があったか話して。"],
  "dress up": ["We dressed up for the party.", "私たちはパーティーのために着飾った。"],
  "eat out": ["Let's eat out tonight.", "今夜は外食しよう。"],
  "fall apart": ["My old shoes are falling apart.", "古い靴がぼろぼろになってきた。"],
  "fall asleep": ["I fell asleep on the train.", "電車で眠ってしまった。"],
  "fall behind": ["Don't fall behind in class.", "授業に遅れないようにね。"],

  // ===== 熟語・慣用表現 =====
  "a piece of cake": ["The test was a piece of cake.", "テストは楽勝だった。"],
  "break the ice": ["A joke helped break the ice.", "冗談のおかげで場が和んだ。"],
  "hit the sack": ["I'm tired. I'll hit the sack.", "疲れた。もう寝るよ。"],
  "under the weather": ["I'm feeling under the weather today.", "今日はちょっと体調が悪い。"],
  "once in a while": ["We eat out once in a while.", "私たちはたまに外食する。"],
  "on purpose": ["He broke it on purpose.", "彼はわざとそれを壊した。"],
  "by accident": ["I deleted the file by accident.", "うっかりファイルを消してしまった。"],
  "in a hurry": ["Sorry, I'm in a hurry now.", "ごめん、今急いでいるんだ。"],
  "out of the blue": ["She called me out of the blue.", "彼女から突然電話がきた。"],
  "cost an arm and a leg": ["This bag cost an arm and a leg.", "このバッグはものすごく高かった。"],
  "hang in there": ["Hang in there. You're almost done.", "頑張って。もう少しで終わりだよ。"],
  "it's up to you": ["Pizza or sushi? It's up to you.", "ピザか寿司か？あなた次第だよ。"],
  "make sense": ["Your explanation makes sense.", "あなたの説明は筋が通っている。"],
  "no big deal": ["Don't worry. It's no big deal.", "心配しないで。大したことないよ。"],
  "sooner or later": ["Sooner or later you'll find out.", "遅かれ早かれ分かるよ。"],
  "take it easy": ["Take it easy this weekend.", "週末はゆっくりしなよ。"],
  "hit it off": ["We hit it off right away.", "私たちはすぐに意気投合した。"],
  "get the hang of": ["You'll get the hang of it soon.", "すぐにコツをつかめるよ。"],
  "ring a bell": ["That name rings a bell.", "その名前は聞き覚えがある。"],
  "sleep on it": ["Let me sleep on it.", "一晩考えさせて。"],
  "call it a day": ["Let's call it a day.", "今日はここまでにしよう。"],
  "give it a shot": ["I've never tried, but I'll give it a shot.", "やったことないけど、試してみるよ。"],
  "grab a bite": ["Let's grab a bite before the movie.", "映画の前に軽く食べよう。"],
  "in the long run": ["Reading pays off in the long run.", "読書は長い目で見れば報われる。"],
  "on the other hand": ["It's cheap. On the other hand, it breaks easily.", "安い。その一方で壊れやすい。"],
  "in other words": ["In other words, we need more time.", "言い換えれば、もっと時間が必要だ。"],
  "by the way": ["By the way, how is your family?", "ところで、ご家族は元気？"],
  "after all": ["He didn't come after all.", "彼は結局来なかった。"],
  "as usual": ["He was late as usual.", "彼はいつものように遅刻した。"],
  "right away": ["I'll send it right away.", "すぐに送ります。"],
  "from now on": ["From now on, I'll get up early.", "これからは早起きします。"],
  "so far": ["So far, everything is fine.", "今のところすべて順調だ。"],
  "in fact": ["In fact, I've never been there.", "実は行ったことがないんだ。"],
  "no wonder": ["No wonder you're tired.", "道理で疲れているわけだ。"],
  "come to think of it": ["Come to think of it, I saw him yesterday.", "そういえば、昨日彼を見かけたな。"],
  "to be honest": ["To be honest, I don't like it.", "正直に言うと、好きじゃない。"],
  "kind of": ["I'm kind of busy right now.", "今ちょっと忙しいんだ。"],
  "for good": ["He left Japan for good.", "彼は日本を永久に離れた。"],
  "on time": ["The train arrived on time.", "電車は時間通りに着いた。"],
  "in time": ["We got there just in time.", "私たちはぎりぎり間に合った。"],
  "at first": ["At first, I didn't like him.", "最初は彼のことが好きじゃなかった。"],
  "at least": ["It takes at least an hour.", "少なくとも1時間はかかる。"],
  "as soon as": ["Call me as soon as you arrive.", "着いたらすぐ電話して。"],
  "all of a sudden": ["All of a sudden, it started raining.", "突然雨が降り出した。"],
  "at the same time": ["They laughed at the same time.", "彼らは同時に笑った。"],
  "for a while": ["I lived in Tokyo for a while.", "しばらく東京に住んでいた。"],
  "in person": ["I want to thank you in person.", "直接会ってお礼を言いたい。"],
  "on one's own": ["She fixed the bike on her own.", "彼女は自分で自転車を直した。"],
  "in advance": ["Please book a table in advance.", "前もって席を予約してください。"],
  "in charge of": ["She is in charge of sales.", "彼女は営業を担当している。"],
  "in the middle of": ["I'm in the middle of dinner.", "今夕食の真っ最中なんだ。"],
  "out of order": ["The elevator is out of order.", "エレベーターは故障中だ。"],
  "out of stock": ["Sorry, that item is out of stock.", "すみません、その商品は在庫切れです。"],
  "day off": ["Tomorrow is my day off.", "明日は休みの日だ。"],
  "be about to": ["I was about to call you.", "ちょうど電話しようとしていたところだ。"],
  "be supposed to": ["You are supposed to be here by nine.", "9時までにここに来ることになっているよ。"],
  "be likely to": ["It is likely to rain tonight.", "今夜は雨が降りそうだ。"],
  "be used to": ["I'm used to getting up early.", "早起きには慣れている。"],
  "be worth doing": ["This movie is worth watching.", "この映画は見る価値がある。"],
  "can't help doing": ["I can't help laughing.", "笑わずにいられない。"],
  "feel like doing": ["I feel like eating ramen.", "ラーメンを食べたい気分だ。"],
  "would rather": ["I would rather stay home.", "むしろ家にいたい。"],
  "might as well": ["We might as well walk.", "歩いたほうがましだね。"],
  "used to do": ["I used to play soccer.", "昔はよくサッカーをしたものだ。"],
  "make sure": ["Make sure the door is locked.", "ドアの鍵を確認して。"],
  "make a difference": ["Small habits make a difference.", "小さな習慣が違いを生む。"],
  "make fun of": ["Don't make fun of your brother.", "弟をからかわないで。"],
  "make up one's mind": ["I made up my mind to study abroad.", "留学しようと決心した。"],
  "change one's mind": ["I changed my mind about the trip.", "旅行について気が変わった。"],
  "lose one's temper": ["He rarely loses his temper.", "彼はめったにかっとならない。"],
  "take advantage of": ["Take advantage of this chance.", "このチャンスをうまく利用して。"],
  "take part in": ["I took part in the contest.", "私はそのコンテストに参加した。"],
  "take a look at": ["Take a look at this photo.", "この写真を見てみて。"],
  "take one's time": ["Take your time. No rush.", "ゆっくりでいいよ。急がないで。"],
  "pay attention to": ["Pay attention to the teacher.", "先生の話に注意を払いなさい。"],
  "get in trouble": ["He got in trouble at school.", "彼は学校で問題を起こした。"],
  "have no idea": ["I have no idea where he is.", "彼がどこにいるのか全く分からない。"],
  "have something to do with": ["He has something to do with the accident.", "彼はその事故と何か関係がある。"],
  "It depends.": ["Will you go? — It depends.", "「行くの？」「場合によるね」"],
  "never mind": ["Never mind. It was nothing.", "気にしないで。何でもないよ。"],
  "not at all": ["Thank you so much! — Not at all.", "「ありがとう！」「どういたしまして」"],
  "so to speak": ["He is, so to speak, a walking dictionary.", "彼はいわば歩く辞書だ。"],
  "believe it or not": ["Believe it or not, I won first prize.", "信じられないかもしれないけど、優勝したんだ。"],
  "as far as I know": ["As far as I know, the store is closed today.", "私の知る限り、その店は今日休みだ。"],
  "if I were you": ["If I were you, I would apologize.", "私があなたなら謝るよ。"],
  "the other day": ["I met her the other day.", "先日彼女に会ったよ。"],
  "these days": ["Everyone is busy these days.", "最近はみんな忙しい。"],
  "in the first place": ["Why did you go there in the first place?", "そもそもなぜそこに行ったの？"],
  "first of all": ["First of all, let me introduce myself.", "まず最初に自己紹介させてください。"],
  "one after another": ["Problems came one after another.", "問題が次から次へと起きた。"],
  "each other": ["They helped each other.", "彼らはお互いに助け合った。"],
  "instead of": ["Drink tea instead of coffee.", "コーヒーの代わりにお茶を飲んで。"],
  "thanks to": ["Thanks to you, we made it.", "あなたのおかげでうまくいったよ。"],
  "due to": ["The flight was delayed due to snow.", "雪が原因で飛行機が遅れた。"],
  "according to": ["According to the news, it will snow.", "ニュースによると雪が降るらしい。"],
  "in spite of": ["We went out in spite of the rain.", "雨にもかかわらず出かけた。"],
  "as long as": ["You can stay as long as you like.", "好きなだけいていいよ。"],
  "in case": ["Take an umbrella in case it rains.", "雨に備えて傘を持って行って。"],
  "no matter what": ["I'll support you no matter what.", "何があっても君を支えるよ。"],
  "on the way": ["I bought coffee on the way to work.", "仕事に行く途中でコーヒーを買った。"],
  "up to date": ["Keep your software up to date.", "ソフトウェアは最新の状態にしておいて。"],
  "second-hand": ["I bought a second-hand bike.", "中古の自転車を買った。"],
  "brand-new": ["He showed me his brand-new phone.", "彼は真新しいスマホを見せてくれた。"],
  "long story short": ["Long story short, we missed the train.", "手短に言うと、電車を逃したんだ。"],
  "you know what": ["You know what? I passed the exam!", "ねえ聞いて！試験に受かったよ！"],
  "what's going on": ["What's going on over there?", "あそこで何が起きてるの？"],
  "how come": ["How come you didn't call me?", "どうして電話くれなかったの？"],
  "what if": ["What if it rains tomorrow?", "もし明日雨だったらどうする？"],
  "sounds good": ["Lunch at noon? Sounds good.", "昼にランチ？いいね。"],
  "my bad": ["Oh, my bad. I forgot to tell you.", "ああ、ごめん。言い忘れてた。"],
  "fair enough": ["I was tired. — Fair enough.", "「疲れてたんだ」「まあ、それなら分かるよ」"],
  "so what": ["I failed once. So what?", "一度失敗した。だから何？"],
  "who knows": ["Maybe he'll come back. Who knows?", "彼は戻ってくるかもね。誰にも分からないけど。"],
  "guess what": ["Guess what! I got the job!", "聞いて！仕事が決まったんだ！"],
  "kill time": ["I read magazines to kill time.", "時間をつぶすために雑誌を読んだ。"],
  "run late": ["Sorry, I'm running late.", "ごめん、遅れそうなんだ。"],
  "text someone": ["Text me when you get home.", "家に着いたらメッセージ送ってね。"],
  "make it": ["Can you make it to the party?", "パーティーに来られる？"],
  "work from home": ["I work from home on Fridays.", "金曜は在宅勤務なんだ。"],
  "be into": ["She is really into yoga.", "彼女はヨガに本当にはまっている。"],
  "be over": ["The meeting is over.", "会議は終わったよ。"],
  "be on one's way": ["I'm on my way now.", "今向かっているところだよ。"],
  "on second thought": ["On second thought, let's stay home.", "考え直したけど、家にいよう。"],
  "to make matters worse": ["To make matters worse, it started to rain.", "さらに悪いことに、雨が降り出した。"],
  "needless to say": ["Needless to say, health comes first.", "言うまでもなく、健康が第一だ。"],
  "It's a shame.": ["You can't come? It's a shame.", "来られないの？残念だな。"],
  "It can't be helped.": ["The event was canceled. It can't be helped.", "イベントは中止か。仕方ないね。"],
  "It's worth it.": ["The hike is hard, but it's worth it.", "その登山はきついけど、それだけの価値があるよ。"],

  // ===== 句動詞・追加 =====
  "ask out": ["He finally asked her out.", "彼はついに彼女をデートに誘った。"],
  "ask around": ["I'll ask around about a good dentist.", "いい歯医者がないか聞いて回るよ。"],
  "act up": ["My laptop is acting up again.", "またパソコンの調子が悪い。"],
  "add up": ["His story doesn't add up.", "彼の話はつじつまが合わない。"],
  "back off": ["Back off and give me some space.", "少し下がって、そっとしておいて。"],
  "brush up on": ["I need to brush up on my English.", "英語を磨き直さないと。"],
  "bump into": ["I bumped into my teacher at the mall.", "モールで先生にばったり会った。"],
  "butt in": ["Sorry to butt in, but I have a question.", "口を挟んですみませんが、質問があります。"],
  "call in sick": ["He called in sick this morning.", "彼は今朝病欠の連絡をした。"],
  "chip in": ["We all chipped in for her gift.", "彼女へのプレゼントにみんなでお金を出し合った。"],
  "come along": ["Want to come along with us?", "私たちと一緒に来る？"],
  "come by": ["Come by my house after work.", "仕事の後うちに寄ってよ。"],
  "cool down": ["Let the soup cool down first.", "まずスープを冷まして。"],
  "cut it out": ["Cut it out! That's annoying.", "やめてよ！うっとうしいな。"],
  "doze off": ["I dozed off during the movie.", "映画の途中でうたた寝してしまった。"],
  "drop in": ["Feel free to drop in anytime.", "いつでも気軽に寄ってね。"],
  "fall for": ["He fell for her at first sight.", "彼は一目で彼女に恋をした。"],
  "fall out": ["They fell out over money.", "彼らはお金のことで仲たがいした。"],
  "follow up": ["I'll follow up with an email.", "メールで追って連絡します。"],
  "freak out": ["Don't freak out. It's just a spider.", "取り乱さないで。ただのクモだよ。"],
  "get around to": ["I finally got around to cleaning my room.", "やっと部屋の掃除に手をつけた。"],
  "get away with": ["You can't get away with lying.", "嘘をついてただで済むと思うなよ。"],
  "get back to": ["I'll get back to you tomorrow.", "明日返事するね。"],
  "get carried away": ["I got carried away and bought too much.", "調子に乗って買いすぎた。"],
  "get it": ["Oh, now I get it.", "ああ、やっと分かった。"],
  "get lost": ["We got lost in the old town.", "旧市街で道に迷った。"],
  "get out of": ["He tried to get out of the meeting.", "彼は会議から逃れようとした。"],
  "give out": ["They are giving out free samples.", "無料サンプルを配っているよ。"],
  "go by": ["Time goes by so fast.", "時間が経つのは本当に早い。"],
  "go down": ["Prices went down last month.", "先月物価が下がった。"],
  "go for": ["I'll go for the cheaper one.", "安いほうを選ぶよ。"],
  "go up": ["The price of gas went up again.", "ガソリンの値段がまた上がった。"],
  "go with": ["This tie goes with your shirt.", "このネクタイはあなたのシャツに合うね。"],
  "goof off": ["Stop goofing off and do your homework.", "サボってないで宿題をしなさい。"],
  "hand over": ["Hand over the keys, please.", "鍵を渡してください。"],
  "head out": ["We're heading out at eight.", "8時に出発するよ。"],
  "head back": ["It's late. Let's head back.", "遅くなったね。帰ろう。"],
  "hear from": ["I haven't heard from him lately.", "最近彼から連絡がない。"],
  "hear of": ["I've never heard of that band.", "そのバンドは聞いたことがない。"],
  "help out": ["Can you help out with the dishes?", "皿洗いを手伝ってくれる？"],
  "hold back": ["Don't hold back. Say what you think.", "遠慮しないで。思っていることを言って。"],
  "hold up": ["Sorry, traffic held me up.", "ごめん、渋滞で遅れたんだ。"],
  "hurry up": ["Hurry up, or we'll miss the bus.", "急いで、バスに乗り遅れるよ。"],
  "kick in": ["The medicine will kick in soon.", "薬はすぐ効いてくるよ。"],
  "kick out": ["He was kicked out of the club.", "彼はクラブから追い出された。"],
  "knock out": ["The long trip knocked me out.", "長旅でくたくたになった。"],
  "lay off": ["The company laid off fifty workers.", "会社は50人を解雇した。"],
  "leave out": ["Don't leave out any details.", "細かいことも抜かさないで。"],
  "let go of": ["Let go of my hand.", "手を離して。"],
  "let in": ["Open the window and let in some air.", "窓を開けて空気を入れて。"],
  "lighten up": ["Lighten up! It was just a joke.", "そんなに深刻にならないで！ただの冗談だよ。"],
  "line up": ["People lined up for the new phone.", "人々が新しいスマホのために並んだ。"],
  "lock up": ["Don't forget to lock up before you leave.", "出る前に戸締まりを忘れないで。"],
  "look around": ["We looked around the old castle.", "私たちは古いお城を見て回った。"],
  "mess up": ["I messed up my presentation.", "プレゼンをしくじった。"],
  "mix up": ["I always mix up their names.", "いつも彼らの名前を混同してしまう。"],
  "move in": ["We moved in last week.", "先週引っ越してきたんだ。"],
  "move out": ["She moved out of her parents' house.", "彼女は実家を出た。"],
  "narrow down": ["Let's narrow down the choices to three.", "選択肢を3つに絞ろう。"],
  "pass on": ["I'll pass on dessert, thanks.", "デザートは遠慮しておくよ、ありがとう。"],
  "pay off": ["All your hard work will pay off.", "努力はきっと報われるよ。"],
  "pick out": ["Help me pick out a birthday gift.", "誕生日プレゼントを選ぶのを手伝って。"],
  "pile up": ["Work is piling up this week.", "今週は仕事がたまっていく。"],
  "plug in": ["Plug in your phone before bed.", "寝る前にスマホを充電して。"],
  "pop up": ["An ad popped up on my screen.", "画面に広告がひょっこり出てきた。"],
  "print out": ["Please print out this document.", "この書類を印刷してください。"],
  "pull off": ["Nobody thought we could pull it off.", "誰も私たちがやり遂げられるとは思っていなかった。"],
  "put back": ["Put the book back on the shelf.", "本を棚に戻して。"],
  "reach out": ["Feel free to reach out anytime.", "いつでも気軽に連絡してね。"],
  "rip off": ["That shop ripped me off.", "あの店にぼったくられた。"],
  "rule out": ["We can't rule out that possibility.", "その可能性は除外できない。"],
  "screw up": ["I screwed up the interview.", "面接で大失敗した。"],
  "see off": ["We saw her off at the airport.", "空港で彼女を見送った。"],
  "sell out": ["The tickets sold out in an hour.", "チケットは1時間で売り切れた。"],
  "set aside": ["Set aside some money every month.", "毎月いくらかお金を取っておきなさい。"],
  "set off": ["We set off early in the morning.", "私たちは朝早く出発した。"],
  "shop around": ["Shop around before you buy.", "買う前にいろいろ見比べてね。"],
  "show around": ["I'll show you around the city.", "街を案内してあげるよ。"],
  "shut down": ["The factory shut down last year.", "その工場は去年閉鎖された。"],
  "sleep in": ["I sleep in on Sundays.", "日曜日は遅くまで寝ている。"],
  "sleep over": ["Can I sleep over at Ken's house?", "ケンの家に泊まってもいい？"],
  "speak up": ["Speak up. I can't hear you.", "もっと大きな声で。聞こえないよ。"],
  "split up": ["Let's split up and look for it.", "手分けして探そう。"],
  "stand up for": ["Stand up for what you believe.", "自分の信じることを守り抜きなさい。"],
  "stop by": ["I'll stop by the store on my way home.", "帰りに店にちょっと寄るね。"],
  "stress out": ["Exams really stress me out.", "試験は本当にストレスだ。"],
  "swing by": ["Can you swing by the bank today?", "今日銀行に寄ってきてくれる？"],
  "take back": ["I take back what I said.", "さっき言ったことは撤回するよ。"],
  "take down": ["Let me take down your address.", "住所を書き取らせてください。"],
  "take in": ["It was a lot of information to take in.", "一度に理解するには情報が多すぎた。"],
  "talk over": ["Let's talk it over during lunch.", "昼食を食べながらじっくり話し合おう。"],
  "team up": ["We teamed up for the project.", "私たちはそのプロジェクトでチームを組んだ。"],
  "tell apart": ["I can't tell the twins apart.", "その双子を見分けられない。"],
  "throw up": ["The child threw up on the bus.", "その子はバスで吐いてしまった。"],
  "tidy up": ["Tidy up your desk before you go.", "帰る前に机を片付けて。"],
  "turn into": ["The rain turned into snow.", "雨が雪に変わった。"],
  "wear out": ["I wore out my running shoes.", "ランニングシューズがすり減ってしまった。"],
  "wind up": ["We wound up ordering pizza again.", "結局またピザを注文する羽目になった。"],
  "wipe out": ["The marathon wiped me out.", "マラソンでへとへとになった。"],
  "work on": ["I'm working on a new project.", "新しいプロジェクトに取り組んでいる。"],
  "wrap up": ["Let's wrap up the meeting.", "会議を切り上げよう。"],
  "zone out": ["I zoned out during the lecture.", "講義中ぼーっとしてしまった。"],
  "zoom in": ["Zoom in on the photo to see it better.", "写真を拡大してよく見て。"],

  // ===== 会話頻出表現・追加 =====
  "What's up?": ["Hey, what's up? — Not much.", "「よう、調子どう？」「まあまあかな」"],
  "long time no see": ["Long time no see! How have you been?", "久しぶり！元気だった？"],
  "no worries": ["Sorry I'm late. — No worries.", "「遅れてごめん」「大丈夫だよ」"],
  "my pleasure": ["Thanks for your help. — My pleasure.", "「手伝ってくれてありがとう」「喜んで」"],
  "don't mention it": ["Thank you so much. — Don't mention it.", "「本当にありがとう」「お礼には及ばないよ」"],
  "it's on me": ["Lunch is on me today.", "今日のランチは私のおごりだよ。"],
  "my treat": ["Let's get dessert. My treat.", "デザート食べよう。私がごちそうするよ。"],
  "good for you": ["I got the job! — Good for you!", "「仕事が決まった！」「よかったね！」"],
  "help yourself": ["Help yourself to some snacks.", "お菓子をご自由にどうぞ。"],
  "after you": ["After you. — Oh, thank you.", "「お先にどうぞ」「あら、ありがとう」"],
  "I mean it.": ["Stop that. I mean it.", "やめて。本気で言ってるんだよ。"],
  "you name it": ["Sushi, pizza, curry... you name it, we have it.", "寿司、ピザ、カレー…何でもそろってるよ。"],
  "It's a deal.": ["I'll pay half. — It's a deal.", "「半分払うよ」「それで決まりだ」"],
  "It's a long story.": ["Why were you late? — It's a long story.", "「なんで遅れたの？」「話せば長くなるんだ」"],
  "speak of the devil": ["Speak of the devil! We were just talking about you.", "噂をすれば！ちょうど君の話をしてたんだ。"],
  "better late than never": ["He finally apologized. Better late than never.", "彼はやっと謝った。遅くてもしないよりましだね。"],
  "easier said than done": ["Just relax? Easier said than done.", "リラックスしろって？言うのは簡単だけどね。"],
  "when it comes to": ["When it comes to cooking, she's the best.", "料理のこととなると、彼女が一番だ。"],
  "at the end of the day": ["At the end of the day, family matters most.", "何だかんだ言って結局、家族が一番大事だ。"],
  "for the time being": ["I'll stay at my parents' house for the time being.", "当分の間は実家にいるよ。"],
  "off the top of my head": ["Off the top of my head, maybe ten people.", "ぱっと思いつく限りでは、10人くらいかな。"],
  "on the tip of my tongue": ["His name is on the tip of my tongue.", "彼の名前が喉まで出かかってるんだけど。"],
  "get cold feet": ["He got cold feet before the speech.", "彼はスピーチの直前に怖気づいた。"],
  "have a crush on": ["She has a crush on her classmate.", "彼女はクラスメートに片思いしている。"],
  "in the mood for": ["I'm in the mood for Italian food.", "イタリアンが食べたい気分だ。"],
  "keep an eye on": ["Keep an eye on my bag, please.", "私のかばんを見ていてください。"],
  "keep track of": ["I use an app to keep track of my spending.", "アプリで支出を把握している。"],
  "lose track of": ["I lost track of time while reading.", "読書していて時間を忘れてしまった。"],
  "make ends meet": ["It's hard to make ends meet these days.", "最近は家計のやりくりが大変だ。"],
  "on the same page": ["Let's make sure we're on the same page.", "認識が合っているか確認しよう。"],
  "play it by ear": ["No plans yet. Let's play it by ear.", "まだ予定はないよ。臨機応変にいこう。"],
  "pull someone's leg": ["Relax, I'm just pulling your leg.", "落ち着いて、ただからかってるだけだよ。"],
  "take a rain check": ["Can I take a rain check on dinner?", "夕食はまた今度にしてもらえる？"],
  "have second thoughts": ["I'm having second thoughts about the plan.", "その計画について迷いが出てきた。"],
  "so far so good": ["How's the new job? — So far so good.", "「新しい仕事はどう？」「今のところ順調だよ」"],
  "spill the beans": ["Who spilled the beans about the party?", "パーティーのこと、誰がばらしたの？"],
  "take it for granted": ["Don't take clean water for granted.", "きれいな水を当たり前だと思わないで。"],
  "the bottom line": ["The bottom line is we need more time.", "結論は、もっと時間が必要だということだ。"],
  "up in the air": ["Our travel plans are still up in the air.", "旅行の計画はまだ未定だ。"],
  "worth a shot": ["It might not work, but it's worth a shot.", "うまくいかないかもしれないけど、試す価値はあるよ。"],
  "you never know": ["Buy a ticket. You never know.", "チケットを買いなよ。先のことは分からないよ。"],
  "hit the road": ["It's getting late. Let's hit the road.", "遅くなってきた。そろそろ出発しよう。"],
  "in the same boat": ["We're all in the same boat here.", "私たちはみんな同じ境遇だよ。"],
  "keep it up": ["Your English is improving. Keep it up!", "英語が上達してるね。その調子！"],
  "know by heart": ["I know this song by heart.", "この歌は全部そらで歌える。"],
  "last but not least": ["Last but not least, thank you all.", "最後になりましたが、皆さんありがとう。"],
  "make yourself at home": ["Come in and make yourself at home.", "入ってくつろいでね。"],
  "mind your own business": ["Why do you ask? Mind your own business.", "なんで聞くの？余計なお世話だよ。"],
  "none of your business": ["How much do I earn? None of your business.", "収入がいくらかって？あなたには関係ないよ。"],
  "no offense": ["No offense, but I don't like this color.", "悪気はないんだけど、この色は好きじゃない。"],
  "not a big fan of": ["I'm not a big fan of horror movies.", "ホラー映画はあまり好きじゃないんだ。"],
  "off the record": ["Off the record, the boss is leaving soon.", "ここだけの話、上司はもうすぐ辞めるよ。"],
  "out of nowhere": ["A cat appeared out of nowhere.", "猫がどこからともなく現れた。"],
  "over the moon": ["She was over the moon about the news.", "彼女はその知らせに大喜びだった。"],
  "rule of thumb": ["As a rule of thumb, save ten percent.", "大まかな目安として、1割は貯金しよう。"],
  "safe and sound": ["They arrived home safe and sound.", "彼らは無事に家に着いた。"],
  "be sick of": ["I'm sick of this rainy weather.", "この雨続きにはうんざりだ。"],
  "be fed up with": ["I'm fed up with his excuses.", "彼の言い訳にはもう我慢の限界だ。"],
  "the sooner the better": ["When should I start? — The sooner the better.", "「いつ始めるべき？」「早ければ早いほどいいよ」"],
  "That's a relief.": ["The test is canceled? That's a relief.", "テストが中止？ほっとしたよ。"],
  "That's too bad.": ["I can't come tonight. — That's too bad.", "「今夜行けないんだ」「それは残念だね」"],
  "to be fair": ["To be fair, he did try his best.", "公平に言えば、彼は全力を尽くしたよ。"],
  "to begin with": ["To begin with, we don't have enough money.", "そもそも、お金が足りないんだ。"],
  "touch base": ["Let's touch base next week.", "来週また軽く連絡を取り合おう。"],
  "under control": ["Don't worry. Everything is under control.", "心配しないで。すべて順調に進んでいるよ。"],
  "word of mouth": ["The cafe became popular by word of mouth.", "そのカフェは口コミで人気になった。"],
  "you have a point": ["You have a point there.", "それは一理あるね。"],
  "catch you later": ["I have to go. Catch you later!", "もう行かなきゃ。じゃあまた後で！"],
  "can't wait": ["I can't wait for summer vacation.", "夏休みが待ちきれない。"],
  "count me in": ["A barbecue party? Count me in!", "バーベキュー？私も入れて！"],
  "I'm down.": ["Movie night? — I'm down.", "「映画の夜やる？」「いいね、乗った」"],
  "cut to the chase": ["Let's cut to the chase. How much is it?", "本題に入ろう。いくらなの？"],
  "fingers crossed": ["Fingers crossed for your interview!", "面接うまくいくよう祈ってるよ！"],
  "for what it's worth": ["For what it's worth, I think you did well.", "参考までに言うと、君はよくやったと思うよ。"],
  "get the picture": ["No money, no time... I get the picture.", "お金も時間もない…状況は分かったよ。"],
  "give me a hand": ["Can you give me a hand with this box?", "この箱を運ぶのに手を貸してくれる？"],
  "go with the flow": ["Don't stress. Just go with the flow.", "気負わないで。流れに任せよう。"],
  "no hard feelings": ["You won this time. No hard feelings.", "今回は君の勝ちだ。恨みっこなしだよ。"],
  "in a nutshell": ["In a nutshell, the project failed.", "一言で言えば、プロジェクトは失敗した。"],
  "It slipped my mind.": ["The meeting! It totally slipped my mind.", "会議だ！完全にうっかり忘れてた。"],
  "keep in touch": ["Let's keep in touch after graduation.", "卒業しても連絡を取り合おうね。"],
  "kill two birds with one stone": ["Walking to work kills two birds with one stone.", "徒歩通勤は一石二鳥だ。"],
  "let it go": ["It was years ago. Let it go.", "何年も前のことだよ。水に流しなよ。"],
  "look on the bright side": ["Look on the bright side. You learned a lot.", "良い面を見なよ。たくさん学べたじゃないか。"],
  "miss the point": ["You're missing the point.", "論点がずれてるよ。"],
  "now and then": ["I still see him now and then.", "今でも時々彼に会うよ。"],
  "on a budget": ["We traveled Europe on a budget.", "私たちは節約しながらヨーロッパを旅した。"],
  "on the dot": ["The meeting starts at nine on the dot.", "会議は9時ぴったりに始まる。"],
  "out of shape": ["I'm out of shape these days.", "最近体がなまっている。"],
  "pros and cons": ["Let's list the pros and cons.", "良い点と悪い点を書き出そう。"],
  "put yourself in my shoes": ["Put yourself in my shoes for a moment.", "ちょっと私の立場になって考えてみてよ。"],
  "read between the lines": ["Read between the lines of her message.", "彼女のメッセージの行間を読んでみて。"],
  "run in the family": ["Good eyesight runs in the family.", "目がいいのは家系なんだ。"],
  "see eye to eye": ["We don't always see eye to eye.", "私たちはいつも意見が合うわけではない。"],
  "sit tight": ["Sit tight. The doctor will see you soon.", "そのままお待ちください。すぐ先生が診ますよ。"],
  "Something came up.": ["Sorry, something came up. I can't make it.", "ごめん、急用ができて行けなくなった。"],
  "speak one's mind": ["Don't be afraid to speak your mind.", "遠慮せず思ったことを言って。"],
  "take turns": ["We take turns washing the dishes.", "私たちは交代で皿洗いをしている。"],
  "the more the merrier": ["Can I bring friends? — Sure, the more the merrier!", "「友達を連れてきていい？」「もちろん、多いほど楽しいよ！」"],
  "Time flies.": ["Time flies. It's already December.", "時間が経つのは早いね。もう12月だ。"],
  "to some extent": ["I agree with you to some extent.", "ある程度はあなたに賛成だ。"],
  "twenty-four seven": ["The store is open twenty-four seven.", "その店は年中無休で開いている。"],
  "under pressure": ["He works well under pressure.", "彼はプレッシャーの中でも良い仕事をする。"],
  "wait and see": ["Will it work? Let's wait and see.", "うまくいくかな？成り行きを見守ろう。"],
  "Way to go!": ["You passed the test? Way to go!", "テストに受かったの？よくやった！"],
  "What a coincidence!": ["You're here too? What a coincidence!", "君もここにいたの？なんという偶然！"],
  "with flying colors": ["She passed the exam with flying colors.", "彼女は見事な成績で試験に合格した。"],
  "You can say that again.": ["This summer is too hot. — You can say that again.", "「今年の夏は暑すぎる」「全くその通りだね」"],
  "Tell me about it.": ["Mondays are the worst. — Tell me about it.", "「月曜は最悪だ」「ほんとそれ」"],
  "break a leg": ["Your concert is tonight? Break a leg!", "今夜コンサート？頑張って！"],
  "call the shots": ["The manager calls the shots here.", "ここでは部長が決定権を握っている。"],
  "cross one's mind": ["It never crossed my mind to quit.", "辞めるなんて考えは頭に浮かばなかった。"],
  "do the trick": ["A little salt will do the trick.", "塩を少し入れればうまくいくよ。"],
  "down to earth": ["She's famous but very down to earth.", "彼女は有名なのにとても気さくだ。"],
  "drive someone crazy": ["This noise is driving me crazy.", "この騒音でおかしくなりそうだ。"],
  "feel free to": ["Feel free to ask questions.", "遠慮なく質問してください。"],
  "few and far between": ["Good chances are few and far between.", "良いチャンスはめったにない。"],
  "food for thought": ["Her speech gave me food for thought.", "彼女のスピーチは考えさせられる内容だった。"],
  "get a grip": ["Get a grip. Panicking won't help.", "しっかりして。慌てても仕方ないよ。"],
  "give someone a ride": ["I'll give you a ride to the station.", "駅まで車で送ってあげるよ。"],
  "give the benefit of the doubt": ["Let's give him the benefit of the doubt.", "とりあえず彼を信じてあげよう。"],
  "go Dutch": ["Let's go Dutch tonight.", "今夜は割り勘にしよう。"],
  "hands down": ["This is hands down the best ramen in town.", "これは文句なしに町一番のラーメンだ。"],
  "have a blast": ["We had a blast at the festival.", "お祭りは最高に楽しかった。"],
  "have a hunch": ["I have a hunch he'll win.", "彼が勝つような予感がする。"],
  "hit the spot": ["This cold beer really hits the spot.", "この冷たいビール、まさに最高だ。"],
  "in the meantime": ["Dinner is at seven. In the meantime, relax.", "夕食は7時。それまでゆっくりしてて。"],
  "It serves you right.": ["You stayed up too late? It serves you right.", "夜更かししすぎた？自業自得だよ。"],
  "jump to conclusions": ["Don't jump to conclusions before hearing him.", "彼の話を聞く前に早合点しないで。"],
  "keep one's word": ["He always keeps his word.", "彼はいつも約束を守る。"],
  "learn the ropes": ["It took a month to learn the ropes.", "仕事のコツを覚えるのに1か月かかった。"],
  "make room for": ["Make room for one more person.", "もう一人分の場所を空けて。"],
  "no strings attached": ["The offer is free, no strings attached.", "その提案は無料で、何の条件もないよ。"],
  "not my cup of tea": ["Golf is not my cup of tea.", "ゴルフは私の好みではない。"],
  "on cloud nine": ["He's been on cloud nine since the wedding.", "彼は結婚式からずっと有頂天だ。"],
  "on short notice": ["Thanks for coming on such short notice.", "急なお願いだったのに来てくれてありがとう。"],
  "once and for all": ["Let's settle this once and for all.", "これを最後にきっぱり決着をつけよう。"],
  "out of hand": ["The party got out of hand.", "パーティーは手に負えなくなった。"],
  "over and over": ["I listened to the song over and over.", "その曲を何度も繰り返し聴いた。"],
  "pick someone's brain": ["Can I pick your brain about marketing?", "マーケティングについて知恵を借りてもいい？"],
  "pull an all-nighter": ["I pulled an all-nighter before the exam.", "試験前に徹夜した。"],
  "right off the bat": ["She answered right off the bat.", "彼女は即座に答えた。"],
  "second to none": ["Their service is second to none.", "彼らのサービスは誰にも負けない。"],
  "take a break": ["Let's take a break for ten minutes.", "10分休憩しよう。"],
  "take my word for it": ["The cake is amazing. Take my word for it.", "そのケーキは絶品だよ。私の言葉を信じて。"],
  "the ball is in your court": ["I've done my part. The ball is in your court.", "私の役目は果たした。次はあなたが決める番だ。"],
  "throw in the towel": ["Don't throw in the towel yet.", "まだ降参しないで。"],
  "to say the least": ["The movie was boring, to say the least.", "控えめに言っても、その映画は退屈だった。"],
  "treat someone to": ["I'll treat you to lunch today.", "今日は昼ご飯をおごるよ。"],
  "up to something": ["The kids are quiet. They're up to something.", "子どもたちが静かだ。何か企んでいるな。"],
  "vice versa": ["I help her, and vice versa.", "私は彼女を助けるし、その逆もまた同じだ。"],
  "when pigs fly": ["He'll clean his room when pigs fly.", "彼が部屋を掃除するなんて絶対にありえない。"],
  "win-win": ["This deal is a win-win for both companies.", "この取引は両社にとってウィンウィンだ。"],
  "work like a charm": ["The new recipe worked like a charm.", "新しいレシピは驚くほどうまくいった。"],
  "drop the ball": ["Sorry, I dropped the ball on this one.", "ごめん、この件は私のミスだ。"],
  "in hot water": ["He's in hot water with his boss.", "彼は上司との関係でまずい立場にある。"],
  "third wheel": ["I felt like a third wheel on their date.", "彼らのデートで邪魔者になった気分だった。"],
  "take it or leave it": ["Fifty dollars. Take it or leave it.", "50ドルだ。嫌なら結構。"],
  "a long shot": ["It's a long shot, but let's apply.", "見込みは薄いけど、応募してみよう。"],
  "That figures.": ["He's late again? That figures.", "彼また遅刻？やっぱりね。"],
  "Here you go.": ["One coffee, please. — Here you go.", "「コーヒーを一つください」「はい、どうぞ」"],
  "There you go.": ["I finally did it! — There you go!", "「ついにできた！」「その調子！」"],
  "It's about time.": ["He apologized. — It's about time.", "「彼が謝ったよ」「やっとか」"],
  "better safe than sorry": ["Wear a helmet. Better safe than sorry.", "ヘルメットをかぶって。用心に越したことはないよ。"],
  "No pain, no gain.": ["Training is hard, but no pain, no gain.", "トレーニングはきついけど、苦労なくして得るものなしだ。"],
  "Practice makes perfect.": ["Keep practicing. Practice makes perfect.", "練習を続けて。習うより慣れろだよ。"],
  "It is what it is.": ["We lost the game. It is what it is.", "試合に負けた。まあ、そういうものさ。"],
  "That works for me.": ["How about Friday? — That works for me.", "「金曜はどう？」「私はそれで大丈夫」"],
  "Suit yourself.": ["I'm not going. — Suit yourself.", "「私は行かない」「お好きにどうぞ」"],
  "Beats me.": ["Where are my keys? — Beats me.", "「私の鍵どこ？」「さっぱり分からない」"],
  "It's a small world.": ["You know my cousin? It's a small world!", "私のいとこを知ってるの？世間は狭いね！"],
  "Now you're talking.": ["Let's order pizza. — Now you're talking!", "「ピザを頼もう」「そうこなくちゃ！」"],
  "That makes two of us.": ["I'm so nervous. — That makes two of us.", "「すごく緊張する」「私も同じだよ」"],
  "Take care.": ["See you next week. Take care!", "また来週。気をつけてね！"],
  "No way.": ["He won the lottery? No way!", "彼が宝くじに当たった？まさか！"],
  "You bet.": ["Can you help me move? — You bet.", "「引っ越し手伝ってくれる？」「もちろん」"],
  "Why not?": ["Want to join us? — Why not?", "「一緒に来る？」「もちろんいいよ」"],
  "Never better.": ["How are you? — Never better.", "「元気？」「絶好調だよ」"],
  "not really": ["Do you like natto? — Not really.", "「納豆好き？」「そうでもないかな」"],
  "sort of": ["Are you tired? — Sort of.", "「疲れてる？」「まあね」"],
  "for real": ["Is he moving to Paris for real?", "彼がパリに引っ越すってマジなの？"],
  "No kidding.": ["I met a famous actor. — No kidding!", "「有名な俳優に会ったんだ」「マジで！」"],
  "Good call.": ["Let's take a taxi. — Good call.", "「タクシーで行こう」「いい判断だね」"],
  "Nice try.": ["Can I skip homework? — Nice try.", "「宿題サボっていい？」「残念でした」"],
  "make do with": ["We made do with what we had.", "あるもので間に合わせた。"],
  "in no time": ["The pizza arrived in no time.", "ピザはあっという間に届いた。"],
  "for ages": ["I haven't seen you for ages!", "すごく久しぶりだね！"],
  "as a matter of fact": ["As a matter of fact, I know him well.", "実を言うと、彼のことはよく知っているんだ。"],
  "by all means": ["May I use your phone? — By all means.", "「電話をお借りしても？」「ぜひどうぞ」"],
  "by no means": ["This problem is by no means easy.", "この問題は決して簡単ではない。"],
  "at all costs": ["We must avoid war at all costs.", "何としても戦争は避けなければならない。"],
  "behind schedule": ["The construction is behind schedule.", "工事は予定より遅れている。"],
  "ahead of schedule": ["We finished ahead of schedule.", "予定より早く終わった。"],
  "in the end": ["In the end, everything worked out.", "最終的にはすべてうまくいった。"],
  "at the moment": ["She's busy at the moment.", "彼女は今ちょうど忙しい。"],
  "any minute now": ["The bus should come any minute now.", "バスは今にも来るはずだ。"],
  "back and forth": ["We emailed back and forth all day.", "一日中メールをやり取りした。"],
  "every other day": ["I go jogging every other day.", "一日おきにジョギングをしている。"],
  "in a row": ["Our team won five games in a row.", "うちのチームは5連勝した。"],
  "on and off": ["It rained on and off all day.", "一日中雨が降ったりやんだりした。"],
  "here and there": ["There were flowers here and there.", "あちこちに花が咲いていた。"],
  "little by little": ["Little by little, my English improved.", "少しずつ英語が上達した。"],
  "more or less": ["The work is more or less done.", "仕事はだいたい終わった。"],
  "on average": ["I sleep seven hours on average.", "平均すると7時間寝ている。"],
  "one by one": ["The students left one by one.", "生徒たちは一人ずつ帰っていった。"],
  "step by step": ["Learn the basics step by step.", "基礎を一歩一歩学ぼう。"],
  "as well": ["I'd like some water as well.", "水ももらえますか。"],
  "as well as": ["She speaks French as well as English.", "彼女は英語だけでなくフランス語も話す。"],
  "in terms of": ["In terms of price, this one is better.", "価格の観点では、こちらのほうがいい。"],
  "regardless of": ["Anyone can join regardless of age.", "年齢に関係なく誰でも参加できる。"],
  "along with": ["Send the form along with a photo.", "写真と一緒に用紙を送ってください。"],
  "aside from": ["Aside from the price, I love this car.", "値段は別として、この車は気に入っている。"],
  "rather than": ["I'd walk rather than wait for the bus.", "バスを待つよりむしろ歩きたい。"],
  "no longer": ["He no longer works here.", "彼はもうここでは働いていない。"],
  "not to mention": ["He speaks Chinese, not to mention English.", "彼は英語は言うまでもなく中国語も話す。"],
  "let alone": ["I can't ride a bike, let alone drive.", "自転車にも乗れないのに、まして運転なんて。"],
  "on top of that": ["I was tired, and on top of that, hungry.", "疲れていたし、その上お腹もすいていた。"],
  "as for": ["As for me, I prefer tea.", "私について言えば、お茶のほうが好きだ。"],
  "as if": ["He talks as if he knew everything.", "彼はまるで何でも知っているかのように話す。"],
  "in order to": ["I save money in order to travel.", "旅行するためにお金を貯めている。"],
  "be willing to": ["I'm willing to help anytime.", "いつでも喜んで手伝うよ。"],
  "be bound to": ["She's bound to succeed.", "彼女はきっと成功するはずだ。"],
  "be dying to": ["I'm dying to see the new movie.", "その新作映画が見たくてたまらない。"],
  "be on the fence": ["I'm still on the fence about moving.", "引っ越すかどうかまだ決めかねている。"],
  "be broke": ["I can't go out. I'm broke.", "出かけられないよ。金欠なんだ。"],
  "be starving": ["What's for dinner? I'm starving.", "夕食は何？お腹ぺこぺこだよ。"]
};
