extra_words = [
    # 頻出動詞フレーズ・補足
    ("abolish", "廃止する"),
    ("accelerate", "加速する"),
    ("accumulate", "蓄積する"),
    ("acknowledge", "認める"),
    ("activate", "起動する"),
    ("adhere", "固執する"),
    ("admire", "称賛する"),
    ("amplify", "増幅する"),
    ("anticipate", "予測する"),
    ("appreciate", "感謝する"),
    ("approve", "承認する"),
    ("assess", "評価する"),
    ("attain", "達成する"),
    ("attribute", "〜に帰する"),
    ("balance", "バランスを取る"),
    ("ban", "禁止する"),
    ("behave", "振る舞う"),
    ("boost", "高める"),
    ("cancel", "キャンセルする"),
    ("capture", "捕まえる"),
    ("challenge", "挑戦する"),
    ("characterize", "特徴づける"),
    ("charge", "請求する"),
    ("cite", "引用する"),
    ("classify", "分類する"),
    ("close", "閉める"),
    ("collapse", "崩壊する"),
    ("communicate", "伝える"),
    ("complain", "不満を言う"),
    ("concentrate", "集中する"),
    ("condemn", "非難する"),
    ("confuse", "混乱させる"),
    ("construct", "建設する"),
    ("consult", "相談する"),
    ("convert", "変換する"),
    ("convince", "納得させる"),
    ("correct", "訂正する"),
    ("count", "数える"),
    ("criticize", "批判する"),
    ("customize", "カスタマイズする"),
    ("debate", "討論する"),
    ("decrease", "減らす"),
    ("deny", "否定する"),
    ("deserve", "値する"),
    ("design", "設計する"),
    ("detect", "検知する"),
    ("devote", "捧げる"),
    ("differ", "異なる"),
    ("disagree", "同意しない"),
    ("disclose", "開示する"),
    ("dismiss", "解雇する"),
    ("dissolve", "溶解する"),
    ("dominate", "支配する"),
    ("ease", "和らげる"),
    ("elect", "選出する"),
    ("emerge", "出現する"),
    ("emit", "排出する"),
    ("employ", "雇う"),
    ("enrich", "豊かにする"),
    ("ensure", "確保する"),
    ("execute", "実行する"),
    ("exhibit", "展示する"),
    ("expand", "拡大する"),
    ("extract", "抽出する"),
    ("facilitate", "促進する"),
    ("finalize", "最終確定する"),
    ("forecast", "予測する"),
    ("form", "形成する"),
    ("fulfill", "履行する"),
    ("gather", "集める"),
    ("generate", "生成する"),
    ("govern", "統治する"),
    ("grasp", "把握する"),
    ("hire", "雇う"),
    ("implement", "実装する"),
    ("import", "輸入する"),
    ("impose", "課す"),
    ("improve", "改善する"),
    ("indicate", "示す"),
    ("initiate", "始める"),
    ("inquire", "尋ねる"),
    ("inspect", "検査する"),
    ("install", "インストールする"),
    ("interact", "相互作用する"),
    ("interpret", "解釈する"),
    ("introduce", "紹介する"),
    ("isolate", "隔離する"),
    ("issue", "発行する"),
    ("justify", "正当化する"),
    ("label", "ラベルを貼る"),
    ("limit", "制限する"),
    ("link", "リンクする"),
    ("list", "列挙する"),
    ("locate", "位置を突き止める"),
    ("maintain", "維持する"),
    ("maximize", "最大化する"),
    ("minimize", "最小化する"),
    ("negotiate", "交渉する"),
    ("notify", "知らせる"),
    ("observe", "観察する"),
    ("overcome", "克服する"),
    ("pause", "一時停止する"),
    ("perform", "実行する"),
    ("plan", "計画する"),
    ("predict", "予測する"),
    ("preserve", "保存する"),
    ("proceed", "進む"),
    ("protest", "抗議する"),
    ("publish", "出版する"),
    ("question", "質問する"),
    ("rank", "ランク付けする"),
    ("reach", "到達する"),
    ("rebuild", "再建する"),
    ("record", "記録する"),
    ("reform", "改革する"),
    ("refuse", "断る"),
    ("reinforce", "強化する"),
    ("release", "リリースする"),
    ("remove", "除去する"),
    ("renew", "更新する"),
    ("report", "報告する"),
    ("reproduce", "繁殖する"),
    ("research", "研究する"),
    ("reserve", "予約する"),
    ("reshape", "形を変える"),
    ("restrict", "制限する"),
    ("reveal", "明かす"),
    ("review", "レビューする"),
    ("revive", "復活させる"),
    ("rotate", "回転する"),
    ("satisfy", "満足させる"),
    ("scale", "スケールする"),
    ("schedule", "スケジュールを立てる"),
    ("secure", "確保する"),
    ("shift", "変わる"),
    ("signal", "合図する"),
    ("simplify", "単純化する"),
    ("sort", "並べる"),
    ("specify", "明記する"),
    ("stabilize", "安定させる"),
    ("strengthen", "強化する"),
    ("supplement", "補う"),
    ("switch", "切り替える"),
    ("target", "標的にする"),
    ("trace", "追跡する"),
    ("track", "追う"),
    ("transfer", "移す"),
    ("treat", "治療する"),
    ("unite", "統合する"),
    ("utilize", "利用する"),
    ("validate", "検証する"),
    ("vary", "変わる"),
    ("visualize", "視覚化する"),
    ("warn", "警告する"),
    # 名詞追加（自然・地理）
    ("altitude", "高度"),
    ("bay", "湾"),
    ("canyon", "峡谷"),
    ("cape", "岬"),
    ("cliff", "崖"),
    ("coast", "海岸"),
    ("continent", "大陸"),
    ("delta", "デルタ"),
    ("dune", "砂丘"),
    ("equator", "赤道"),
    ("estuary", "河口"),
    ("glacier", "氷河"),
    ("gorge", "峡谷"),
    ("hemisphere", "半球"),
    ("hill", "丘"),
    ("inlet", "入り江"),
    ("latitude", "緯度"),
    ("longitude", "経度"),
    ("marsh", "湿地"),
    ("meadow", "草原"),
    ("peninsula", "半島"),
    ("plain", "平原"),
    ("plateau", "高原"),
    ("pole", "極"),
    ("reef", "岩礁"),
    ("swamp", "沼"),
    ("terrain", "地形"),
    ("waterfall", "滝"),
    ("wetland", "湿地帯"),
    # 名詞（社会・人間）
    ("ancestor", "先祖"),
    ("childhood", "幼少期"),
    ("citizen", "市民"),
    ("civilization", "文明"),
    ("colleague", "同僚"),
    ("community", "地域社会"),
    ("companion", "仲間"),
    ("descendant", "子孫"),
    ("elder", "年長者"),
    ("employer", "雇用主"),
    ("generation", "世代"),
    ("guardian", "後見人"),
    ("heritage", "遺産"),
    ("immigrant", "移民"),
    ("inhabitant", "住民"),
    ("leader", "指導者"),
    ("minority", "少数民族"),
    ("neighbor", "隣人"),
    ("orphan", "孤児"),
    ("population", "人口"),
    ("refugee", "難民"),
    ("resident", "住民"),
    ("sibling", "きょうだい"),
    ("society", "社会"),
    ("spouse", "配偶者"),
    ("stranger", "見知らぬ人"),
    ("survivor", "生存者"),
    ("veteran", "退役軍人"),
    ("widow", "未亡人"),
    ("youth", "若者"),
    # 名詞（物・道具）
    ("anchor", "錨"),
    ("antenna", "アンテナ"),
    ("barrel", "樽"),
    ("basket", "バスケット"),
    ("bolt", "ボルト"),
    ("bucket", "バケツ"),
    ("button", "ボタン"),
    ("cable", "ケーブル"),
    ("chain", "鎖"),
    ("clip", "クリップ"),
    ("container", "容器"),
    ("crane", "クレーン"),
    ("crystal", "クリスタル"),
    ("cylinder", "シリンダー"),
    ("dial", "ダイヤル"),
    ("engine", "エンジン"),
    ("filter", "フィルター"),
    ("flask", "フラスコ"),
    ("frame", "フレーム"),
    ("fuel", "燃料"),
    ("funnel", "じょうご"),
    ("gear", "ギア"),
    ("generator", "発電機"),
    ("hammer", "ハンマー"),
    ("handle", "ハンドル"),
    ("hinge", "蝶番"),
    ("hook", "フック"),
    ("ladder", "はしご"),
    ("lens", "レンズ"),
    ("lever", "レバー"),
    ("magnet", "磁石"),
    ("mechanism", "仕組み"),
    ("motor", "モーター"),
    ("nail", "釘"),
    ("needle", "針"),
    ("paddle", "パドル"),
    ("panel", "パネル"),
    ("pipe", "パイプ"),
    ("plank", "板"),
    ("platform", "プラットフォーム"),
    ("plug", "プラグ"),
    ("pump", "ポンプ"),
    ("rack", "ラック"),
    ("rod", "棒"),
    ("rope", "ロープ"),
    ("sail", "帆"),
    ("screw", "ネジ"),
    ("sensor", "センサー"),
    ("socket", "ソケット"),
    ("spring", "バネ"),
    ("switch", "スイッチ"),
    ("tank", "タンク"),
    ("terminal", "端末"),
    ("tool", "道具"),
    ("tube", "チューブ"),
    ("valve", "バルブ"),
    ("wire", "ワイヤー"),
    ("wrench", "レンチ"),
    # 形容詞（心理・行動）
    ("abrupt", "突然の"),
    ("accountable", "責任ある"),
    ("adaptable", "適応できる"),
    ("addicted", "中毒になった"),
    ("affectionate", "愛情深い"),
    ("agitated", "動揺した"),
    ("alert", "注意深い"),
    ("ambitious", "野心的な"),
    ("assertive", "自己主張の強い"),
    ("attentive", "注意を払っている"),
    ("biased", "偏った"),
    ("bold", "大胆な"),
    ("cautious", "慎重な"),
    ("coherent", "一貫した"),
    ("compassionate", "思いやりのある"),
    ("compatible", "互換性のある"),
    ("compliant", "従順な"),
    ("concise", "簡潔な"),
    ("considerate", "思いやりのある"),
    ("consistent", "首尾一貫した"),
    ("corrupt", "腐敗した"),
    ("courageous", "勇敢な"),
    ("creative", "創造的な"),
    ("credible", "信頼できる"),
    ("cynical", "皮肉な"),
    ("determined", "決意した"),
    ("devoted", "献身的な"),
    ("discontent", "不満な"),
    ("dominant", "優位な"),
    ("empathetic", "共感できる"),
    ("enduring", "耐久性のある"),
    ("ethical", "倫理的な"),
    ("fair", "公平な"),
    ("faithful", "忠実な"),
    ("familiar", "親しみのある"),
    ("fearless", "恐れ知らずの"),
    ("firm", "固い"),
    ("frank", "率直な"),
    ("frugal", "節約する"),
    ("genuine", "本物の"),
    ("grateful", "感謝している"),
    ("gregarious", "社交的な"),
    ("hardworking", "勤勉な"),
    ("honest", "正直な"),
    ("hopeful", "希望に満ちた"),
    ("immoral", "不道徳な"),
    ("impatient", "短気な"),
    ("impulsive", "衝動的な"),
    ("independent", "独立した"),
    ("indifferent", "無関心な"),
    ("industrious", "勤勉な"),
    ("influential", "影響力のある"),
    ("innovative", "革新的な"),
    ("insightful", "洞察力のある"),
    ("inspiring", "感動的な"),
    ("intelligent", "頭の良い"),
    ("introverted", "内向的な"),
    ("lively", "活発な"),
    ("loyal", "忠実な"),
    ("mature", "成熟した"),
    ("moral", "道徳的な"),
    ("motivated", "やる気がある"),
    ("objective", "客観的な"),
    ("observant", "観察力のある"),
    ("open", "開放的な"),
    ("optimistic", "楽観的な"),
    ("outspoken", "率直な"),
    ("passionate", "情熱的な"),
    ("patient", "忍耐強い"),
    ("perceptive", "知覚の鋭い"),
    ("persistent", "粘り強い"),
    ("pessimistic", "悲観的な"),
    ("playful", "遊び好きな"),
    ("principled", "主義を持った"),
    ("proactive", "積極的な"),
    ("prudent", "慎重な"),
    ("punctual", "時間を守る"),
    ("rational", "合理的な"),
    ("realistic", "現実的な"),
    ("rebellious", "反抗的な"),
    ("reliable", "頼りになる"),
    ("reserved", "控えめな"),
    ("resourceful", "臨機応変な"),
    ("respectful", "礼儀正しい"),
    ("responsible", "責任感のある"),
    ("rigid", "頑固な"),
    ("self-aware", "自己認識のある"),
    ("self-disciplined", "自律した"),
    ("sensible", "分別のある"),
    ("sociable", "社交的な"),
    ("spontaneous", "自然発生的な"),
    ("stubborn", "頑固な"),
    ("sympathetic", "同情的な"),
    ("thoughtful", "思慮深い"),
    ("tolerant", "寛容な"),
    ("trustworthy", "信頼できる"),
    ("unbiased", "偏りのない"),
    ("understanding", "理解ある"),
    ("virtuous", "有徳の"),
    ("witty", "機知に富む"),
    # 接続・関係詞（追加）
    ("above all", "何よりも"),
    ("after all", "結局"),
    ("as a result", "結果として"),
    ("as long as", "〜する限り"),
    ("as soon as", "〜するとすぐに"),
    ("at least", "少なくとも"),
    ("at most", "せいぜい"),
    ("at once", "すぐに"),
    ("by contrast", "対照的に"),
    ("due to", "〜のために"),
    ("for example", "例えば"),
    ("for instance", "例えば"),
    ("in addition", "さらに"),
    ("in contrast", "対照的に"),
    ("in fact", "実際に"),
    ("in general", "一般的に"),
    ("in order to", "〜するために"),
    ("in other words", "つまり"),
    ("in particular", "特に"),
    ("in spite of", "〜にもかかわらず"),
    ("in terms of", "〜の観点から"),
    ("in total", "合計で"),
    ("moreover", "さらに"),
    ("nevertheless", "それにもかかわらず"),
    ("on the contrary", "それどころか"),
    ("on the other hand", "一方で"),
    ("to sum up", "まとめると"),
    ("unless", "〜でない限り"),
    ("whereas", "一方で"),
    ("with regard to", "〜に関して"),
    # 追加の一般語彙
    ("ambiance", "雰囲気"),
    ("annex", "別館"),
    ("approval", "承認"),
    ("arrangement", "配置"),
    ("barrier", "障壁"),
    ("bias", "偏り"),
    ("breakthrough", "突破口"),
    ("coalition", "連合"),
    ("coherence", "一貫性"),
    ("commonplace", "ありふれた"),
    ("concentration", "集中"),
    ("contradiction", "矛盾"),
    ("convention", "慣習"),
    ("correlation", "相関"),
    ("coverage", "報道"),
    ("criterion", "基準"),
    ("deliberation", "審議"),
    ("disruption", "混乱"),
    ("distinction", "区別"),
    ("dominance", "優位"),
    ("elaboration", "詳細"),
    ("emphasis", "強調"),
    ("estimation", "見積もり"),
    ("exception", "例外"),
    ("expectation", "期待"),
    ("expertise", "専門知識"),
    ("extension", "延長"),
    ("familiarity", "親しみ"),
    ("flexibility", "柔軟性"),
    ("fluctuation", "変動"),
    ("framework", "枠組み"),
    ("generalization", "一般化"),
    ("hardship", "困難"),
    ("implication", "意味"),
    ("incentive", "動機"),
    ("inconsistency", "矛盾"),
    ("indication", "兆候"),
    ("infrastructure", "インフラ"),
    ("instinct", "本能"),
    ("integrity", "誠実さ"),
    ("interpretation", "解釈"),
    ("justification", "正当化"),
    ("manipulation", "操作"),
    ("mentality", "考え方"),
    ("misconception", "誤解"),
    ("mindset", "考え方"),
    ("momentum", "勢い"),
    ("narrative", "語り"),
    ("norm", "規範"),
    ("notion", "概念"),
    ("nuance", "ニュアンス"),
    ("paradigm", "パラダイム"),
    ("parameter", "パラメーター"),
    ("perception", "認識"),
    ("persistence", "粘り強さ"),
    ("perspective", "視点"),
    ("presumption", "推定"),
    ("procedure", "手順"),
    ("proposition", "提案"),
    ("provision", "条項"),
    ("rationality", "合理性"),
    ("recognition", "認識"),
    ("relevance", "関連性"),
    ("reliability", "信頼性"),
    ("resilience", "回復力"),
    ("rhetoric", "修辞"),
    ("scrutiny", "精査"),
    ("stability", "安定性"),
    ("stereotype", "ステレオタイプ"),
    ("stimulus", "刺激"),
    ("tendency", "傾向"),
    ("transition", "移行"),
    ("transparency", "透明性"),
    ("uncertainty", "不確かさ"),
    ("uniformity", "均一性"),
    ("validity", "妥当性"),
    ("variable", "変数"),
    ("variation", "変動"),
    ("versatility", "多用途性"),
]

import re

with open("words.js", "r", encoding="utf-8") as f:
    content = f.read()

existing = set(re.findall(r'en: "([^"]+)"', content))
print(f"Existing words: {len(existing)}")

new_words = []
for en, ja in extra_words:
    if en not in existing:
        existing.add(en)
        new_words.append((en, ja))

print(f"New words to add: {len(new_words)}")

additional = "".join(f'  {{ en: "{en}", ja: "{ja}" }},\n' for en, ja in new_words)
content = content.rstrip().rstrip(";").rstrip("]").rstrip() + "\n" + additional + "];\n"

with open("words.js", "w", encoding="utf-8") as f:
    f.write(content)

total = len(re.findall(r'en: "', content))
print(f"Total words: {total}")
