const PHRASES = [
  // ===== 句動詞 (Phrasal Verbs) =====
  { en: "get up", ja: "起きる" },
  { en: "get along with", ja: "〜と仲良くやる" },
  { en: "get over", ja: "乗り越える" },
  { en: "get rid of", ja: "取り除く" },
  { en: "get back", ja: "戻る" },
  { en: "get in", ja: "(車に)乗る／中に入る" },
  { en: "get out", ja: "外に出る" },
  { en: "get off", ja: "(電車・バスを)降りる" },
  { en: "get on", ja: "(電車・バスに)乗る" },
  { en: "get through", ja: "切り抜ける／やり終える" },
  { en: "get together", ja: "集まる" },
  { en: "get away", ja: "逃れる／離れる" },
  { en: "get by", ja: "なんとかやっていく" },
  { en: "get into", ja: "夢中になる／入る" },
  { en: "get used to", ja: "〜に慣れる" },
  { en: "get in touch", ja: "連絡を取る" },
  { en: "give up", ja: "あきらめる" },
  { en: "give back", ja: "返す" },
  { en: "give away", ja: "ただであげる" },
  { en: "give in", ja: "屈する／折れる" },
  { en: "go on", ja: "続く／起こる" },
  { en: "go out", ja: "外出する" },
  { en: "go over", ja: "見直す／確認する" },
  { en: "go through", ja: "経験する／詳しく調べる" },
  { en: "go ahead", ja: "先に進む／どうぞ" },
  { en: "go off", ja: "(アラームが)鳴る／爆発する" },
  { en: "come up", ja: "(話題・問題が)持ち上がる" },
  { en: "come up with", ja: "思いつく" },
  { en: "come across", ja: "偶然出くわす" },
  { en: "come over", ja: "(家に)遊びに来る" },
  { en: "come out", ja: "出てくる／発売される" },
  { en: "come down with", ja: "(病気に)かかる" },
  { en: "take off", ja: "離陸する／脱ぐ" },
  { en: "take on", ja: "引き受ける" },
  { en: "take over", ja: "引き継ぐ" },
  { en: "take out", ja: "取り出す／連れ出す" },
  { en: "take up", ja: "始める／(場所を)占める" },
  { en: "take care of", ja: "世話をする" },
  { en: "take after", ja: "(親などに)似ている" },
  { en: "take place", ja: "行われる／起こる" },
  { en: "put on", ja: "着る／身につける" },
  { en: "put off", ja: "延期する" },
  { en: "put up with", ja: "我慢する" },
  { en: "put away", ja: "片付ける" },
  { en: "put out", ja: "(火を)消す" },
  { en: "put down", ja: "置く／書き留める" },
  { en: "put together", ja: "組み立てる／まとめる" },
  { en: "look for", ja: "探す" },
  { en: "look after", ja: "面倒を見る" },
  { en: "look forward to", ja: "楽しみに待つ" },
  { en: "look up", ja: "(辞書などで)調べる" },
  { en: "look into", ja: "調査する" },
  { en: "look out", ja: "気をつける" },
  { en: "look over", ja: "ざっと目を通す" },
  { en: "look up to", ja: "尊敬する" },
  { en: "look down on", ja: "見下す" },
  { en: "turn on", ja: "(電源を)つける" },
  { en: "turn off", ja: "(電源を)消す" },
  { en: "turn up", ja: "現れる／音量を上げる" },
  { en: "turn down", ja: "断る／音量を下げる" },
  { en: "turn out", ja: "結局〜だと分かる" },
  { en: "turn around", ja: "振り向く／好転させる" },
  { en: "turn in", ja: "提出する" },
  { en: "run out of", ja: "使い果たす" },
  { en: "run into", ja: "偶然出会う" },
  { en: "run away", ja: "逃げる" },
  { en: "run errands", ja: "用事を済ませる" },
  { en: "break down", ja: "故障する" },
  { en: "break up", ja: "(恋人と)別れる" },
  { en: "break into", ja: "押し入る" },
  { en: "break out", ja: "(戦争・火事が)発生する" },
  { en: "bring up", ja: "育てる／話題に出す" },
  { en: "bring back", ja: "返す／思い出させる" },
  { en: "bring about", ja: "引き起こす" },
  { en: "call off", ja: "中止する" },
  { en: "call back", ja: "折り返し電話する" },
  { en: "carry on", ja: "続ける" },
  { en: "carry out", ja: "実行する" },
  { en: "catch up with", ja: "追いつく" },
  { en: "check in", ja: "チェックインする" },
  { en: "check out", ja: "調べてみる／チェックアウトする" },
  { en: "cheer up", ja: "元気づける" },
  { en: "clean up", ja: "きれいに片付ける" },
  { en: "count on", ja: "頼りにする" },
  { en: "cut down on", ja: "(量を)減らす" },
  { en: "cut off", ja: "切り離す／遮断する" },
  { en: "deal with", ja: "対処する" },
  { en: "drop by", ja: "立ち寄る" },
  { en: "drop off", ja: "(人・物を)降ろす／届ける" },
  { en: "drop out", ja: "中退する／脱落する" },
  { en: "end up", ja: "結局〜になる" },
  { en: "figure out", ja: "理解する／解き明かす" },
  { en: "fill out", ja: "(書類に)記入する" },
  { en: "find out", ja: "見つけ出す／知る" },
  { en: "fit in", ja: "なじむ／溶け込む" },
  { en: "focus on", ja: "集中する" },
  { en: "grow up", ja: "成長する／大人になる" },
  { en: "hand in", ja: "提出する" },
  { en: "hand out", ja: "配る" },
  { en: "hang on", ja: "ちょっと待つ" },
  { en: "hang out", ja: "(友達と)遊ぶ／ぶらぶらする" },
  { en: "hang up", ja: "電話を切る" },
  { en: "hold on", ja: "待つ／しっかりつかまる" },
  { en: "keep up with", ja: "(遅れずに)ついていく" },
  { en: "keep on", ja: "〜し続ける" },
  { en: "keep in mind", ja: "心に留めておく" },
  { en: "let down", ja: "がっかりさせる" },
  { en: "make up", ja: "仲直りする／でっち上げる" },
  { en: "make up for", ja: "埋め合わせをする" },
  { en: "make out", ja: "理解する／見分ける" },
  { en: "move on", ja: "(次へ)前に進む" },
  { en: "pass away", ja: "亡くなる" },
  { en: "pass out", ja: "気を失う" },
  { en: "pay back", ja: "(お金を)返す" },
  { en: "pick up", ja: "拾う／車で迎えに行く" },
  { en: "point out", ja: "指摘する" },
  { en: "pull over", ja: "車を路肩に停める" },
  { en: "set up", ja: "設立する／設定する" },
  { en: "settle down", ja: "落ち着く／定住する" },
  { en: "show up", ja: "現れる／来る" },
  { en: "show off", ja: "見せびらかす" },
  { en: "sign up", ja: "登録する／申し込む" },
  { en: "slow down", ja: "速度を落とす" },
  { en: "sort out", ja: "整理する／解決する" },
  { en: "stand for", ja: "〜を意味する／表す" },
  { en: "stand out", ja: "目立つ" },
  { en: "stay up", ja: "(寝ずに)起きている" },
  { en: "stick to", ja: "〜を貫く／守る" },
  { en: "think over", ja: "じっくり考える" },
  { en: "throw away", ja: "捨てる" },
  { en: "try on", ja: "試着する" },
  { en: "try out", ja: "試してみる" },
  { en: "wake up", ja: "目を覚ます" },
  { en: "warm up", ja: "準備運動する／温める" },
  { en: "watch out", ja: "気をつける" },
  { en: "work out", ja: "運動する／うまくいく" },
  { en: "write down", ja: "書き留める" },
  { en: "back up", ja: "後押しする／バックアップする" },
  { en: "blow up", ja: "爆発する／激怒する" },
  { en: "calm down", ja: "落ち着く" },
  { en: "dress up", ja: "着飾る／正装する" },
  { en: "eat out", ja: "外食する" },
  { en: "fall apart", ja: "ばらばらに壊れる" },
  { en: "fall asleep", ja: "眠り込む" },
  { en: "fall behind", ja: "遅れをとる" },

  // ===== 熟語・慣用表現 (Idioms & Expressions) =====
  { en: "a piece of cake", ja: "とても簡単なこと" },
  { en: "break the ice", ja: "場の緊張をほぐす" },
  { en: "hit the sack", ja: "寝る" },
  { en: "under the weather", ja: "体調が悪い" },
  { en: "once in a while", ja: "たまに" },
  { en: "on purpose", ja: "わざと" },
  { en: "by accident", ja: "偶然に" },
  { en: "in a hurry", ja: "急いで" },
  { en: "out of the blue", ja: "突然／不意に" },
  { en: "cost an arm and a leg", ja: "非常に高くつく" },
  { en: "hang in there", ja: "くじけずに頑張る" },
  { en: "it's up to you", ja: "あなた次第だ" },
  { en: "make sense", ja: "筋が通る／理解できる" },
  { en: "no big deal", ja: "大したことない" },
  { en: "sooner or later", ja: "遅かれ早かれ" },
  { en: "take it easy", ja: "気楽にやる" },
  { en: "hit it off", ja: "意気投合する" },
  { en: "get the hang of", ja: "コツをつかむ" },
  { en: "ring a bell", ja: "聞き覚えがある" },
  { en: "sleep on it", ja: "一晩考える" },
  { en: "call it a day", ja: "今日はここまでにする" },
  { en: "give it a shot", ja: "試しにやってみる" },
  { en: "grab a bite", ja: "軽く食事する" },
  { en: "in the long run", ja: "長い目で見れば" },
  { en: "on the other hand", ja: "その一方で" },
  { en: "in other words", ja: "言い換えれば" },
  { en: "by the way", ja: "ところで" },
  { en: "after all", ja: "結局のところ" },
  { en: "as usual", ja: "いつものように" },
  { en: "right away", ja: "今すぐに" },
  { en: "from now on", ja: "これからは" },
  { en: "so far", ja: "今のところ" },
  { en: "in fact", ja: "実際のところ" },
  { en: "no wonder", ja: "道理で〜なわけだ" },
  { en: "come to think of it", ja: "そういえば" },
  { en: "to be honest", ja: "正直に言うと" },
  { en: "kind of", ja: "ちょっと／どちらかというと" },
  { en: "for good", ja: "永久に／これを最後に" },
  { en: "on time", ja: "時間通りに" },
  { en: "in time", ja: "間に合って" },
  { en: "at first", ja: "最初は" },
  { en: "at least", ja: "少なくとも" },
  { en: "as soon as", ja: "〜するとすぐに" },
  { en: "all of a sudden", ja: "突然" },
  { en: "at the same time", ja: "同時に" },
  { en: "for a while", ja: "しばらくの間" },
  { en: "in person", ja: "直接会って" },
  { en: "on one's own", ja: "自分の力で／一人で" },
  { en: "in advance", ja: "前もって" },
  { en: "in charge of", ja: "〜を担当して" },
  { en: "in the middle of", ja: "〜の真っ最中で" },
  { en: "out of order", ja: "故障中で" },
  { en: "out of stock", ja: "在庫切れで" },
  { en: "day off", ja: "休みの日" },
  { en: "be about to", ja: "まさに〜しようとしている" },
  { en: "be supposed to", ja: "〜することになっている" },
  { en: "be likely to", ja: "〜しそうである" },
  { en: "be used to", ja: "〜に慣れている" },
  { en: "be worth doing", ja: "〜する価値がある" },
  { en: "can't help doing", ja: "〜せずにいられない" },
  { en: "feel like doing", ja: "〜したい気分だ" },
  { en: "would rather", ja: "むしろ〜したい" },
  { en: "might as well", ja: "〜したほうがましだ" },
  { en: "used to do", ja: "以前はよく〜したものだ" },
  { en: "make sure", ja: "確実に〜する／確認する" },
  { en: "make a difference", ja: "違いを生む／効果がある" },
  { en: "make fun of", ja: "からかう" },
  { en: "make up one's mind", ja: "決心する" },
  { en: "change one's mind", ja: "気が変わる" },
  { en: "lose one's temper", ja: "かっとなる" },
  { en: "take advantage of", ja: "うまく利用する" },
  { en: "take part in", ja: "参加する" },
  { en: "take a look at", ja: "〜を見てみる" },
  { en: "take one's time", ja: "ゆっくりやる" },
  { en: "pay attention to", ja: "注意を払う" },
  { en: "get in trouble", ja: "面倒なことになる" },
  { en: "have no idea", ja: "全く分からない" },
  { en: "have something to do with", ja: "〜と関係がある" },
  { en: "It depends.", ja: "場合による" },
  { en: "never mind", ja: "気にしないで" },
  { en: "not at all", ja: "全然／どういたしまして" },
  { en: "so to speak", ja: "いわば" },
  { en: "believe it or not", ja: "信じられないかもしれないが" },
  { en: "as far as I know", ja: "私の知る限り" },
  { en: "if I were you", ja: "もし私があなたなら" },
  { en: "the other day", ja: "先日" },
  { en: "these days", ja: "最近" },
  { en: "in the first place", ja: "そもそも" },
  { en: "first of all", ja: "まず第一に" },
  { en: "one after another", ja: "次から次へと" },
  { en: "each other", ja: "お互い" },
  { en: "instead of", ja: "〜の代わりに" },
  { en: "thanks to", ja: "〜のおかげで" },
  { en: "due to", ja: "〜が原因で" },
  { en: "according to", ja: "〜によると" },
  { en: "in spite of", ja: "〜にもかかわらず" },
  { en: "as long as", ja: "〜する限り" },
  { en: "in case", ja: "〜する場合に備えて" },
  { en: "no matter what", ja: "何があっても" },
  { en: "on the way", ja: "途中で" },
  { en: "up to date", ja: "最新の" },
  { en: "second-hand", ja: "中古の" },
  { en: "brand-new", ja: "真新しい" },
  { en: "long story short", ja: "手短に言うと" },
  { en: "you know what", ja: "あのね／ねえ聞いて" },
  { en: "what's going on", ja: "何が起きているの／調子どう" },
  { en: "how come", ja: "どうして／なぜ" },
  { en: "what if", ja: "もし〜だったらどうする" },
  { en: "sounds good", ja: "いいね" },
  { en: "my bad", ja: "私のミスだ／ごめん" },
  { en: "fair enough", ja: "もっともだ／なるほどね" },
  { en: "so what", ja: "だから何" },
  { en: "who knows", ja: "誰にも分からない" },
  { en: "guess what", ja: "ねえ、聞いて(何だと思う?)" },
  { en: "kill time", ja: "時間をつぶす" },
  { en: "run late", ja: "(予定より)遅れている" },
  { en: "text someone", ja: "メッセージを送る" },
  { en: "make it", ja: "間に合う／成功する／都合がつく" },
  { en: "work from home", ja: "在宅勤務する" },
  { en: "be into", ja: "〜にはまっている" },
  { en: "be over", ja: "終わっている" },
  { en: "be on one's way", ja: "向かっている途中だ" },
  { en: "on second thought", ja: "考え直してみると" },
  { en: "to make matters worse", ja: "さらに悪いことに" },
  { en: "needless to say", ja: "言うまでもなく" },
  { en: "It's a shame.", ja: "残念だ" },
  { en: "It can't be helped.", ja: "仕方がない" },
  { en: "It's worth it.", ja: "それだけの価値がある" }
];
