const PHRASES = [
  // ===== 句動詞 (Phrasal Verbs) =====
  { en: "get up", ja: "起きる" },
  { en: "get along with", ja: "〜と仲良くやる" },
  { en: "get over", ja: "乗り越える" },
  { en: "get rid of", ja: "取り除く" },
  { en: "get back", ja: "戻る" },
  { en: "get in", ja: "(車に)乗る／中に入る" },
  { en: "get out", ja: "外に出る" },
  { en: "get off", ja: "(電車・バスを)降りる" },
  { en: "get on", ja: "(電車・バスに)乗る" },
  { en: "get through", ja: "切り抜ける／やり終える" },
  { en: "get together", ja: "集まる" },
  { en: "get away", ja: "逃れる／離れる" },
  { en: "get by", ja: "なんとかやっていく" },
  { en: "get into", ja: "夢中になる／入る" },
  { en: "get used to", ja: "〜に慣れる" },
  { en: "get in touch", ja: "連絡を取る" },
  { en: "give up", ja: "あきらめる" },
  { en: "give back", ja: "返す" },
  { en: "give away", ja: "ただであげる" },
  { en: "give in", ja: "屈する／折れる" },
  { en: "go on", ja: "続く／起こる" },
  { en: "go out", ja: "外出する" },
  { en: "go over", ja: "見直す／確認する" },
  { en: "go through", ja: "経験する／詳しく調べる" },
  { en: "go ahead", ja: "先に進む／どうぞ" },
  { en: "go off", ja: "(アラームが)鳴る／爆発する" },
  { en: "come up", ja: "(話題・問題が)持ち上がる" },
  { en: "come up with", ja: "思いつく" },
  { en: "come across", ja: "偶然出くわす" },
  { en: "come over", ja: "(家に)遊びに来る" },
  { en: "come out", ja: "出てくる／発売される" },
  { en: "come down with", ja: "(病気に)かかる" },
  { en: "take off", ja: "離陸する／脱ぐ" },
  { en: "take on", ja: "引き受ける" },
  { en: "take over", ja: "引き継ぐ" },
  { en: "take out", ja: "取り出す／連れ出す" },
  { en: "take up", ja: "始める／(場所を)占める" },
  { en: "take care of", ja: "世話をする" },
  { en: "take after", ja: "(親などに)似ている" },
  { en: "take place", ja: "行われる／起こる" },
  { en: "put on", ja: "着る／身につける" },
  { en: "put off", ja: "延期する" },
  { en: "put up with", ja: "我慢する" },
  { en: "put away", ja: "片付ける" },
  { en: "put out", ja: "(火を)消す" },
  { en: "put down", ja: "置く／書き留める" },
  { en: "put together", ja: "組み立てる／まとめる" },
  { en: "look for", ja: "探す" },
  { en: "look after", ja: "面倒を見る" },
  { en: "look forward to", ja: "楽しみに待つ" },
  { en: "look up", ja: "(辞書などで)調べる" },
  { en: "look into", ja: "調査する" },
  { en: "look out", ja: "(危険に)注意する" },
  { en: "look over", ja: "ざっと目を通す" },
  { en: "look up to", ja: "尊敬する" },
  { en: "look down on", ja: "見下す" },
  { en: "turn on", ja: "(電源を)つける" },
  { en: "turn off", ja: "(電源を)消す" },
  { en: "turn up", ja: "現れる／音量を上げる" },
  { en: "turn down", ja: "断る／音量を下げる" },
  { en: "turn out", ja: "結局〜だと分かる" },
  { en: "turn around", ja: "振り向く／好転させる" },
  { en: "turn in", ja: "(課題を)提出する／床につく" },
  { en: "run out of", ja: "使い果たす" },
  { en: "run into", ja: "偶然出会う" },
  { en: "run away", ja: "逃げる" },
  { en: "run errands", ja: "用事を済ませる" },
  { en: "break down", ja: "故障する" },
  { en: "break up", ja: "(恋人と)別れる" },
  { en: "break into", ja: "押し入る" },
  { en: "break out", ja: "(戦争・火事が)発生する" },
  { en: "bring up", ja: "育てる／話題に出す" },
  { en: "bring back", ja: "返す／思い出させる" },
  { en: "bring about", ja: "引き起こす" },
  { en: "call off", ja: "中止する" },
  { en: "call back", ja: "折り返し電話する" },
  { en: "carry on", ja: "続ける" },
  { en: "carry out", ja: "実行する" },
  { en: "catch up with", ja: "追いつく" },
  { en: "check in", ja: "チェックインする" },
  { en: "check out", ja: "調べてみる／チェックアウトする" },
  { en: "cheer up", ja: "元気づける" },
  { en: "clean up", ja: "きれいに片付ける" },
  { en: "count on", ja: "頼りにする" },
  { en: "cut down on", ja: "(量を)減らす" },
  { en: "cut off", ja: "切り離す／遮断する" },
  { en: "deal with", ja: "対処する" },
  { en: "drop by", ja: "立ち寄る" },
  { en: "drop off", ja: "(人・物を)降ろす／届ける" },
  { en: "drop out", ja: "中退する／脱落する" },
  { en: "end up", ja: "結局〜になる" },
  { en: "figure out", ja: "理解する／解き明かす" },
  { en: "fill out", ja: "(書類に)記入する" },
  { en: "find out", ja: "見つけ出す／知る" },
  { en: "fit in", ja: "なじむ／溶け込む" },
  { en: "focus on", ja: "集中する" },
  { en: "grow up", ja: "成長する／大人になる" },
  { en: "hand in", ja: "提出する" },
  { en: "hand out", ja: "配る" },
  { en: "hang on", ja: "ちょっと待つ" },
  { en: "hang out", ja: "(友達と)遊ぶ／ぶらぶらする" },
  { en: "hang up", ja: "電話を切る" },
  { en: "hold on", ja: "待つ／しっかりつかまる" },
  { en: "keep up with", ja: "(遅れずに)ついていく" },
  { en: "keep on", ja: "〜し続ける" },
  { en: "keep in mind", ja: "心に留めておく" },
  { en: "let down", ja: "がっかりさせる" },
  { en: "make up", ja: "仲直りする／でっち上げる" },
  { en: "make up for", ja: "埋め合わせをする" },
  { en: "make out", ja: "理解する／見分ける" },
  { en: "move on", ja: "(次へ)前に進む" },
  { en: "pass away", ja: "亡くなる" },
  { en: "pass out", ja: "気を失う" },
  { en: "pay back", ja: "(お金を)返す" },
  { en: "pick up", ja: "拾う／車で迎えに行く" },
  { en: "point out", ja: "指摘する" },
  { en: "pull over", ja: "車を路肩に停める" },
  { en: "set up", ja: "設立する／設定する" },
  { en: "settle down", ja: "落ち着く／定住する" },
  { en: "show up", ja: "現れる／来る" },
  { en: "show off", ja: "見せびらかす" },
  { en: "sign up", ja: "登録する／申し込む" },
  { en: "slow down", ja: "速度を落とす" },
  { en: "sort out", ja: "整理する／解決する" },
  { en: "stand for", ja: "〜を意味する／表す" },
  { en: "stand out", ja: "目立つ" },
  { en: "stay up", ja: "(寝ずに)起きている" },
  { en: "stick to", ja: "〜を貫く／守る" },
  { en: "think over", ja: "じっくり考える" },
  { en: "throw away", ja: "捨てる" },
  { en: "try on", ja: "試着する" },
  { en: "try out", ja: "試してみる" },
  { en: "wake up", ja: "目を覚ます" },
  { en: "warm up", ja: "準備運動する／温める" },
  { en: "watch out", ja: "気をつける" },
  { en: "work out", ja: "運動する／うまくいく" },
  { en: "write down", ja: "書き留める" },
  { en: "back up", ja: "後押しする／バックアップする" },
  { en: "blow up", ja: "爆発する／激怒する" },
  { en: "calm down", ja: "落ち着く" },
  { en: "dress up", ja: "着飾る／正装する" },
  { en: "eat out", ja: "外食する" },
  { en: "fall apart", ja: "ばらばらに壊れる" },
  { en: "fall asleep", ja: "眠り込む" },
  { en: "fall behind", ja: "遅れをとる" },

  // ===== 熟語・慣用表現 (Idioms & Expressions) =====
  { en: "a piece of cake", ja: "とても簡単なこと" },
  { en: "break the ice", ja: "場の緊張をほぐす" },
  { en: "hit the sack", ja: "寝る" },
  { en: "under the weather", ja: "体調が悪い" },
  { en: "once in a while", ja: "たまに" },
  { en: "on purpose", ja: "わざと" },
  { en: "by accident", ja: "偶然に" },
  { en: "in a hurry", ja: "急いで" },
  { en: "out of the blue", ja: "突然／不意に" },
  { en: "cost an arm and a leg", ja: "非常に高くつく" },
  { en: "hang in there", ja: "くじけずに頑張る" },
  { en: "it's up to you", ja: "あなた次第だ" },
  { en: "make sense", ja: "筋が通る／理解できる" },
  { en: "no big deal", ja: "大したことない" },
  { en: "sooner or later", ja: "遅かれ早かれ" },
  { en: "take it easy", ja: "気楽にやる" },
  { en: "hit it off", ja: "意気投合する" },
  { en: "get the hang of", ja: "コツをつかむ" },
  { en: "ring a bell", ja: "聞き覚えがある" },
  { en: "sleep on it", ja: "一晩考える" },
  { en: "call it a day", ja: "今日はここまでにする" },
  { en: "give it a shot", ja: "試しにやってみる" },
  { en: "grab a bite", ja: "軽く食事する" },
  { en: "in the long run", ja: "長い目で見れば" },
  { en: "on the other hand", ja: "その一方で" },
  { en: "in other words", ja: "言い換えれば" },
  { en: "by the way", ja: "ところで" },
  { en: "after all", ja: "結局のところ" },
  { en: "as usual", ja: "いつものように" },
  { en: "right away", ja: "今すぐに" },
  { en: "from now on", ja: "これからは" },
  { en: "so far", ja: "今のところ" },
  { en: "in fact", ja: "実際のところ" },
  { en: "no wonder", ja: "道理で〜なわけだ" },
  { en: "come to think of it", ja: "そういえば" },
  { en: "to be honest", ja: "正直に言うと" },
  { en: "kind of", ja: "ちょっと／どちらかというと" },
  { en: "for good", ja: "永久に／これを最後に" },
  { en: "on time", ja: "時間通りに" },
  { en: "in time", ja: "間に合って" },
  { en: "at first", ja: "最初は" },
  { en: "at least", ja: "少なくとも" },
  { en: "as soon as", ja: "〜するとすぐに" },
  { en: "all of a sudden", ja: "突然" },
  { en: "at the same time", ja: "同時に" },
  { en: "for a while", ja: "しばらくの間" },
  { en: "in person", ja: "直接会って" },
  { en: "on one's own", ja: "自分の力で／一人で" },
  { en: "in advance", ja: "前もって" },
  { en: "in charge of", ja: "〜を担当して" },
  { en: "in the middle of", ja: "〜の真っ最中で" },
  { en: "out of order", ja: "故障中で" },
  { en: "out of stock", ja: "在庫切れで" },
  { en: "day off", ja: "休みの日" },
  { en: "be about to", ja: "まさに〜しようとしている" },
  { en: "be supposed to", ja: "〜することになっている" },
  { en: "be likely to", ja: "〜しそうである" },
  { en: "be used to", ja: "〜に慣れている" },
  { en: "be worth doing", ja: "〜する価値がある" },
  { en: "can't help doing", ja: "〜せずにいられない" },
  { en: "feel like doing", ja: "〜したい気分だ" },
  { en: "would rather", ja: "むしろ〜したい" },
  { en: "might as well", ja: "〜したほうがましだ" },
  { en: "used to do", ja: "以前はよく〜したものだ" },
  { en: "make sure", ja: "確実に〜する／確認する" },
  { en: "make a difference", ja: "違いを生む／効果がある" },
  { en: "make fun of", ja: "からかう" },
  { en: "make up one's mind", ja: "決心する" },
  { en: "change one's mind", ja: "気が変わる" },
  { en: "lose one's temper", ja: "かっとなる" },
  { en: "take advantage of", ja: "うまく利用する" },
  { en: "take part in", ja: "参加する" },
  { en: "take a look at", ja: "〜を見てみる" },
  { en: "take one's time", ja: "ゆっくりやる" },
  { en: "pay attention to", ja: "注意を払う" },
  { en: "get in trouble", ja: "面倒なことになる" },
  { en: "have no idea", ja: "全く分からない" },
  { en: "have something to do with", ja: "〜と関係がある" },
  { en: "It depends.", ja: "場合による" },
  { en: "never mind", ja: "気にしないで" },
  { en: "not at all", ja: "全然／どういたしまして" },
  { en: "so to speak", ja: "いわば" },
  { en: "believe it or not", ja: "信じられないかもしれないが" },
  { en: "as far as I know", ja: "私の知る限り" },
  { en: "if I were you", ja: "もし私があなたなら" },
  { en: "the other day", ja: "先日" },
  { en: "these days", ja: "最近" },
  { en: "in the first place", ja: "そもそも" },
  { en: "first of all", ja: "まず第一に" },
  { en: "one after another", ja: "次から次へと" },
  { en: "each other", ja: "お互い" },
  { en: "instead of", ja: "〜の代わりに" },
  { en: "thanks to", ja: "〜のおかげで" },
  { en: "due to", ja: "〜が原因で" },
  { en: "according to", ja: "〜によると" },
  { en: "in spite of", ja: "〜にもかかわらず" },
  { en: "as long as", ja: "〜する限り" },
  { en: "in case", ja: "〜する場合に備えて" },
  { en: "no matter what", ja: "何があっても" },
  { en: "on the way", ja: "途中で" },
  { en: "up to date", ja: "最新の" },
  { en: "second-hand", ja: "中古の" },
  { en: "brand-new", ja: "真新しい" },
  { en: "long story short", ja: "手短に言うと" },
  { en: "you know what", ja: "あのね／ねえ聞いて" },
  { en: "what's going on", ja: "何が起きているの／調子どう" },
  { en: "how come", ja: "どうして／なぜ" },
  { en: "what if", ja: "もし〜だったらどうする" },
  { en: "sounds good", ja: "いいね" },
  { en: "my bad", ja: "私のミスだ／ごめん" },
  { en: "fair enough", ja: "もっともだ／なるほどね" },
  { en: "so what", ja: "だから何" },
  { en: "who knows", ja: "誰にも分からない" },
  { en: "guess what", ja: "ねえ、聞いて(何だと思う?)" },
  { en: "kill time", ja: "時間をつぶす" },
  { en: "run late", ja: "(予定より)遅れている" },
  { en: "text someone", ja: "メッセージを送る" },
  { en: "make it", ja: "間に合う／成功する／都合がつく" },
  { en: "work from home", ja: "在宅勤務する" },
  { en: "be into", ja: "〜にはまっている" },
  { en: "be over", ja: "終わっている" },
  { en: "be on one's way", ja: "向かっている途中だ" },
  { en: "on second thought", ja: "考え直してみると" },
  { en: "to make matters worse", ja: "さらに悪いことに" },
  { en: "needless to say", ja: "言うまでもなく" },
  { en: "It's a shame.", ja: "残念だ" },
  { en: "It can't be helped.", ja: "仕方がない" },
  { en: "It's worth it.", ja: "それだけの価値がある" },

  // ===== 句動詞・追加 (More Phrasal Verbs) =====
  { en: "ask out", ja: "デートに誘う" },
  { en: "ask around", ja: "聞いて回る" },
  { en: "act up", ja: "(機械が)調子が悪い／(子どもが)ぐずる" },
  { en: "add up", ja: "計算が合う／つじつまが合う" },
  { en: "back off", ja: "引き下がる" },
  { en: "brush up on", ja: "(勉強し直して)磨きをかける" },
  { en: "bump into", ja: "ばったり出会う" },
  { en: "butt in", ja: "口を挟む／割り込む" },
  { en: "call in sick", ja: "電話で病欠を伝える" },
  { en: "chip in", ja: "お金を出し合う" },
  { en: "come along", ja: "一緒に来る／(物事が)進む" },
  { en: "come by", ja: "立ち寄る／手に入れる" },
  { en: "cool down", ja: "冷める／頭を冷やす" },
  { en: "cut it out", ja: "(嫌なことを)やめる" },
  { en: "doze off", ja: "うたた寝する" },
  { en: "drop in", ja: "ふらっと訪ねる" },
  { en: "fall for", ja: "恋に落ちる／(嘘に)だまされる" },
  { en: "fall out", ja: "仲たがいする" },
  { en: "follow up", ja: "追って確認・連絡する" },
  { en: "freak out", ja: "取り乱す／パニックになる" },
  { en: "get around to", ja: "(後回しにしていたことを)やっとやる" },
  { en: "get away with", ja: "(悪事の)罰を逃れる" },
  { en: "get back to", ja: "(人に)あとで返事をする" },
  { en: "get carried away", ja: "調子に乗る／夢中になりすぎる" },
  { en: "get it", ja: "理解する／分かる" },
  { en: "get lost", ja: "道に迷う" },
  { en: "get out of", ja: "(義務・約束から)逃れる" },
  { en: "give out", ja: "配る／(力が)尽きる" },
  { en: "go by", ja: "(時が)過ぎる" },
  { en: "go down", ja: "下がる／(事が)起こる" },
  { en: "go for", ja: "〜を選ぶ／狙う" },
  { en: "go up", ja: "上がる" },
  { en: "go with", ja: "〜に合う／〜に決める" },
  { en: "goof off", ja: "サボる／ふざける" },
  { en: "hand over", ja: "手渡す／引き渡す" },
  { en: "head out", ja: "出かける" },
  { en: "head back", ja: "帰路につく" },
  { en: "hear from", ja: "〜から連絡をもらう" },
  { en: "hear of", ja: "〜のことを聞いたことがある" },
  { en: "help out", ja: "手を貸す" },
  { en: "hold back", ja: "ためらう／(感情を)抑える" },
  { en: "hold up", ja: "遅らせる／持ちこたえる" },
  { en: "hurry up", ja: "急ぐ" },
  { en: "kick in", ja: "(薬・効果が)効き始める" },
  { en: "kick out", ja: "追い出す" },
  { en: "knock out", ja: "ノックアウトする／疲れ果てさせる" },
  { en: "lay off", ja: "解雇する" },
  { en: "leave out", ja: "抜かす／仲間外れにする" },
  { en: "let go of", ja: "手放す／(握っていた手を)離す" },
  { en: "let in", ja: "中に入れる" },
  { en: "lighten up", ja: "肩の力を抜く／深刻になりすぎない" },
  { en: "line up", ja: "一列に並ぶ" },
  { en: "lock up", ja: "戸締まりをする" },
  { en: "look around", ja: "見て回る" },
  { en: "mess up", ja: "しくじる／散らかす" },
  { en: "mix up", ja: "混同する／取り違える" },
  { en: "move in", ja: "引っ越してくる" },
  { en: "move out", ja: "引っ越して出ていく" },
  { en: "narrow down", ja: "絞り込む" },
  { en: "pass on", ja: "(誘いを)見送る／伝える" },
  { en: "pay off", ja: "(努力が)報われる／完済する" },
  { en: "pick out", ja: "選び出す" },
  { en: "pile up", ja: "積み重なる／たまる" },
  { en: "plug in", ja: "コンセントにつなぐ" },
  { en: "pop up", ja: "ひょっこり現れる" },
  { en: "print out", ja: "印刷する" },
  { en: "pull off", ja: "(難しいことを)やってのける" },
  { en: "put back", ja: "元の場所に戻す" },
  { en: "reach out", ja: "連絡を取る／手を差し伸べる" },
  { en: "rip off", ja: "ぼったくる" },
  { en: "rule out", ja: "可能性から除外する" },
  { en: "screw up", ja: "大失敗する" },
  { en: "see off", ja: "見送る" },
  { en: "sell out", ja: "売り切れる" },
  { en: "set aside", ja: "取っておく／脇に置く" },
  { en: "set off", ja: "出発する／(警報を)作動させる" },
  { en: "shop around", ja: "買う前にあちこち見比べる" },
  { en: "show around", ja: "案内して回る" },
  { en: "shut down", ja: "停止する／閉鎖する" },
  { en: "sleep in", ja: "(休日に)遅くまで寝る" },
  { en: "sleep over", ja: "(友達の家に)泊まる" },
  { en: "speak up", ja: "大きな声で話す／意見を言う" },
  { en: "split up", ja: "別れる／分かれる" },
  { en: "stand up for", ja: "〜を守る／擁護する" },
  { en: "stop by", ja: "ちょっと立ち寄る" },
  { en: "stress out", ja: "ストレスでまいる" },
  { en: "swing by", ja: "ついでに寄る" },
  { en: "take back", ja: "返品する／(発言を)撤回する" },
  { en: "take down", ja: "書き取る／取り外す" },
  { en: "take in", ja: "理解して吸収する／取り込む" },
  { en: "talk over", ja: "じっくり話し合う" },
  { en: "team up", ja: "チームを組む" },
  { en: "tell apart", ja: "見分ける" },
  { en: "throw up", ja: "吐く" },
  { en: "tidy up", ja: "きちんと片付ける" },
  { en: "turn into", ja: "〜に変わる" },
  { en: "wear out", ja: "すり減る／くたくたに疲れさせる" },
  { en: "wind up", ja: "最終的に〜する羽目になる" },
  { en: "wipe out", ja: "全滅させる／へとへとにさせる" },
  { en: "work on", ja: "〜に取り組む" },
  { en: "wrap up", ja: "終わらせる／切り上げる" },
  { en: "zone out", ja: "ぼーっとする" },
  { en: "zoom in", ja: "ズームで拡大する" },

  // ===== 会話頻出表現・追加 (More Conversational Expressions) =====
  { en: "What's up?", ja: "調子どう？／どうしたの？" },
  { en: "long time no see", ja: "久しぶり" },
  { en: "no worries", ja: "心配いらないよ／大丈夫" },
  { en: "my pleasure", ja: "こちらこそ喜んで" },
  { en: "don't mention it", ja: "お礼には及ばないよ" },
  { en: "it's on me", ja: "私のおごりだ" },
  { en: "my treat", ja: "私がごちそうするよ" },
  { en: "good for you", ja: "よかったね" },
  { en: "help yourself", ja: "ご自由にどうぞ" },
  { en: "after you", ja: "お先にどうぞ" },
  { en: "I mean it.", ja: "本気で言っている" },
  { en: "you name it", ja: "何でも／どんなものでも" },
  { en: "It's a deal.", ja: "それで決まりだ" },
  { en: "It's a long story.", ja: "話せば長くなる" },
  { en: "speak of the devil", ja: "噂をすれば" },
  { en: "better late than never", ja: "遅れてもやらないよりまし" },
  { en: "easier said than done", ja: "言うは易く行うは難し" },
  { en: "when it comes to", ja: "〜のこととなると" },
  { en: "at the end of the day", ja: "何だかんだ言って結局は" },
  { en: "for the time being", ja: "当分の間" },
  { en: "off the top of my head", ja: "ぱっと思いつく限りでは" },
  { en: "on the tip of my tongue", ja: "喉まで出かかっている" },
  { en: "get cold feet", ja: "直前で怖気づく" },
  { en: "have a crush on", ja: "〜に片思いしている" },
  { en: "in the mood for", ja: "〜したい気分で" },
  { en: "keep an eye on", ja: "〜から目を離さない" },
  { en: "keep track of", ja: "〜を把握しておく" },
  { en: "lose track of", ja: "〜を見失う" },
  { en: "make ends meet", ja: "家計をやりくりする" },
  { en: "on the same page", ja: "認識が一致している" },
  { en: "play it by ear", ja: "臨機応変にやる" },
  { en: "pull someone's leg", ja: "からかう／かつぐ" },
  { en: "take a rain check", ja: "また今度にしてもらう" },
  { en: "have second thoughts", ja: "迷いが生じる" },
  { en: "so far so good", ja: "今のところ順調" },
  { en: "spill the beans", ja: "うっかり秘密を漏らす" },
  { en: "take it for granted", ja: "当たり前だと思う" },
  { en: "the bottom line", ja: "結論／肝心な点" },
  { en: "up in the air", ja: "まだ未定で" },
  { en: "worth a shot", ja: "試してみる価値がある" },
  { en: "you never know", ja: "先のことは分からないよ" },
  { en: "hit the road", ja: "出発する" },
  { en: "in the same boat", ja: "同じ(苦しい)境遇で" },
  { en: "keep it up", ja: "その調子で続ける" },
  { en: "know by heart", ja: "そらで覚えている" },
  { en: "last but not least", ja: "最後になるが(重要なこと)" },
  { en: "make yourself at home", ja: "くつろいでください" },
  { en: "mind your own business", ja: "余計なお世話だ" },
  { en: "none of your business", ja: "あなたには関係ない" },
  { en: "no offense", ja: "悪気はないんだけど" },
  { en: "not a big fan of", ja: "あまり好きではない" },
  { en: "off the record", ja: "ここだけの話だが" },
  { en: "out of nowhere", ja: "どこからともなく" },
  { en: "over the moon", ja: "大喜びで" },
  { en: "rule of thumb", ja: "経験則／大まかな目安" },
  { en: "safe and sound", ja: "無事に" },
  { en: "be sick of", ja: "〜にうんざりしている" },
  { en: "be fed up with", ja: "〜にはもう我慢の限界だ" },
  { en: "the sooner the better", ja: "早ければ早いほどいい" },
  { en: "That's a relief.", ja: "ほっとした" },
  { en: "That's too bad.", ja: "それは残念だ" },
  { en: "to be fair", ja: "公平に言えば" },
  { en: "to begin with", ja: "そもそも／まず第一に" },
  { en: "touch base", ja: "軽く連絡を取る" },
  { en: "under control", ja: "制御できている" },
  { en: "word of mouth", ja: "口コミ" },
  { en: "you have a point", ja: "一理ある" },
  { en: "catch you later", ja: "じゃあまた後で" },
  { en: "can't wait", ja: "待ちきれない" },
  { en: "count me in", ja: "私も入れて／参加するよ" },
  { en: "I'm down.", ja: "いいね、乗った(参加する)" },
  { en: "cut to the chase", ja: "さっさと本題に入る" },
  { en: "fingers crossed", ja: "うまくいくよう祈ってる" },
  { en: "for what it's worth", ja: "参考までに言うと" },
  { en: "get the picture", ja: "状況を飲み込む" },
  { en: "give me a hand", ja: "手を貸して" },
  { en: "go with the flow", ja: "流れに身を任せる" },
  { en: "no hard feelings", ja: "恨みっこなしだよ" },
  { en: "in a nutshell", ja: "一言で言えば" },
  { en: "It slipped my mind.", ja: "うっかり忘れていた" },
  { en: "keep in touch", ja: "連絡を取り合う" },
  { en: "kill two birds with one stone", ja: "一石二鳥" },
  { en: "let it go", ja: "水に流す／こだわらない" },
  { en: "look on the bright side", ja: "良い面に目を向ける" },
  { en: "miss the point", ja: "要点を外す" },
  { en: "now and then", ja: "時々" },
  { en: "on a budget", ja: "節約中で" },
  { en: "on the dot", ja: "時間ぴったりに" },
  { en: "out of shape", ja: "体がなまって" },
  { en: "pros and cons", ja: "良い点と悪い点" },
  { en: "put yourself in my shoes", ja: "私の立場になって考えて" },
  { en: "read between the lines", ja: "行間を読む" },
  { en: "run in the family", ja: "家系である／血筋だ" },
  { en: "see eye to eye", ja: "意見がぴったり合う" },
  { en: "sit tight", ja: "動かずにじっと待つ" },
  { en: "Something came up.", ja: "急用ができた" },
  { en: "speak one's mind", ja: "思ったことを率直に言う" },
  { en: "take turns", ja: "交代で行う" },
  { en: "the more the merrier", ja: "人数が多いほど楽しい" },
  { en: "Time flies.", ja: "時間が経つのは早い" },
  { en: "to some extent", ja: "ある程度は" },
  { en: "twenty-four seven", ja: "年中無休で／四六時中" },
  { en: "under pressure", ja: "プレッシャーを受けて" },
  { en: "wait and see", ja: "成り行きを見守る" },
  { en: "Way to go!", ja: "よくやった！" },
  { en: "What a coincidence!", ja: "なんという偶然！" },
  { en: "with flying colors", ja: "見事な成績で" },
  { en: "You can say that again.", ja: "全くその通り" },
  { en: "Tell me about it.", ja: "ほんとそれ／わかるよ" },
  { en: "break a leg", ja: "(本番前に)頑張って！" },
  { en: "call the shots", ja: "決定権を握る" },
  { en: "cross one's mind", ja: "ふと頭に浮かぶ" },
  { en: "do the trick", ja: "それで解決する／効果がある" },
  { en: "down to earth", ja: "気取らず現実的な" },
  { en: "drive someone crazy", ja: "人をイライラさせる" },
  { en: "feel free to", ja: "遠慮なく〜してください" },
  { en: "few and far between", ja: "ごくまれな" },
  { en: "food for thought", ja: "考えさせられる材料" },
  { en: "get a grip", ja: "気をしっかり持つ" },
  { en: "give someone a ride", ja: "車で送ってあげる" },
  { en: "give the benefit of the doubt", ja: "疑わしくてもとりあえず信じる" },
  { en: "go Dutch", ja: "割り勘にする" },
  { en: "hands down", ja: "文句なしに／断然" },
  { en: "have a blast", ja: "最高に楽しむ" },
  { en: "have a hunch", ja: "〜という予感がする" },
  { en: "hit the spot", ja: "(飲食物が)まさに欲しかった味だ" },
  { en: "in the meantime", ja: "その間に" },
  { en: "It serves you right.", ja: "自業自得だ" },
  { en: "jump to conclusions", ja: "早合点する" },
  { en: "keep one's word", ja: "約束を守る" },
  { en: "learn the ropes", ja: "仕事のコツを覚える" },
  { en: "make room for", ja: "〜のために場所を空ける" },
  { en: "no strings attached", ja: "見返りの条件なしで" },
  { en: "not my cup of tea", ja: "私の好みではない" },
  { en: "on cloud nine", ja: "有頂天で" },
  { en: "on short notice", ja: "急な話で／直前の連絡で" },
  { en: "once and for all", ja: "これを最後にきっぱりと" },
  { en: "out of hand", ja: "手に負えない" },
  { en: "over and over", ja: "何度も繰り返し" },
  { en: "pick someone's brain", ja: "知恵を借りる" },
  { en: "pull an all-nighter", ja: "徹夜する" },
  { en: "right off the bat", ja: "出だしから即座に" },
  { en: "second to none", ja: "誰にも負けない" },
  { en: "take a break", ja: "休憩する" },
  { en: "take my word for it", ja: "私の言うことを信じて" },
  { en: "the ball is in your court", ja: "次はあなたが決める番" },
  { en: "throw in the towel", ja: "降参する" },
  { en: "to say the least", ja: "控えめに言っても" },
  { en: "treat someone to", ja: "〜をおごる" },
  { en: "up to something", ja: "何か企んでいる" },
  { en: "vice versa", ja: "逆もまた同じ" },
  { en: "when pigs fly", ja: "絶対にありえない" },
  { en: "win-win", ja: "双方に利益がある" },
  { en: "work like a charm", ja: "驚くほどうまくいく" },
  { en: "drop the ball", ja: "(担当のことで)へまをする" },
  { en: "in hot water", ja: "まずい立場で" },
  { en: "third wheel", ja: "(二人きりの)邪魔者" },
  { en: "take it or leave it", ja: "受けるか断るか(交渉の余地なし)" },
  { en: "a long shot", ja: "見込みは薄いがダメ元の賭け" },
  { en: "That figures.", ja: "やっぱりね" },
  { en: "Here you go.", ja: "はい、どうぞ" },
  { en: "There you go.", ja: "その調子／ほらできた" },
  { en: "It's about time.", ja: "やっとか／もうそうすべき頃だ" },
  { en: "better safe than sorry", ja: "用心に越したことはない" },
  { en: "No pain, no gain.", ja: "苦労なくして得るものなし" },
  { en: "Practice makes perfect.", ja: "習うより慣れろ" },
  { en: "It is what it is.", ja: "そういうものだ／仕方ない" },
  { en: "That works for me.", ja: "私はそれで大丈夫" },
  { en: "Suit yourself.", ja: "お好きにどうぞ" },
  { en: "Beats me.", ja: "さっぱり分からない" },
  { en: "It's a small world.", ja: "世間は狭いね" },
  { en: "Now you're talking.", ja: "そうこなくちゃ" },
  { en: "That makes two of us.", ja: "私も同じだ" },
  { en: "Take care.", ja: "気をつけてね／お大事に" },
  { en: "No way.", ja: "まさか／絶対に嫌だ" },
  { en: "You bet.", ja: "もちろん" },
  { en: "Why not?", ja: "もちろんいいよ／やろうよ" },
  { en: "Never better.", ja: "絶好調だ" },
  { en: "not really", ja: "そうでもない" },
  { en: "sort of", ja: "まあね／多少は" },
  { en: "for real", ja: "マジで／本当に" },
  { en: "No kidding.", ja: "冗談でしょ／マジで" },
  { en: "Good call.", ja: "いい判断だ" },
  { en: "Nice try.", ja: "惜しい／残念でした" },
  { en: "make do with", ja: "〜で間に合わせる" },
  { en: "in no time", ja: "あっという間に" },
  { en: "for ages", ja: "長い間／久しく" },
  { en: "as a matter of fact", ja: "実を言うと" },
  { en: "by all means", ja: "ぜひどうぞ" },
  { en: "by no means", ja: "決して〜ない" },
  { en: "at all costs", ja: "何としても" },
  { en: "behind schedule", ja: "予定より遅れて" },
  { en: "ahead of schedule", ja: "予定より早く" },
  { en: "in the end", ja: "最終的には" },
  { en: "at the moment", ja: "ちょうど今は" },
  { en: "any minute now", ja: "今にも／もうすぐ" },
  { en: "back and forth", ja: "行ったり来たり" },
  { en: "every other day", ja: "一日おきに" },
  { en: "in a row", ja: "連続で" },
  { en: "on and off", ja: "断続的に" },
  { en: "here and there", ja: "あちこちで" },
  { en: "little by little", ja: "少しずつ" },
  { en: "more or less", ja: "多かれ少なかれ／だいたい" },
  { en: "on average", ja: "平均すると" },
  { en: "one by one", ja: "一つずつ" },
  { en: "step by step", ja: "一歩一歩着実に" },
  { en: "as well", ja: "〜もまた" },
  { en: "as well as", ja: "〜だけでなく…も" },
  { en: "in terms of", ja: "〜の観点から" },
  { en: "regardless of", ja: "〜に関係なく" },
  { en: "along with", ja: "〜と一緒に" },
  { en: "aside from", ja: "〜は別として" },
  { en: "rather than", ja: "〜よりむしろ" },
  { en: "no longer", ja: "もはや〜ない" },
  { en: "not to mention", ja: "〜は言うまでもなく" },
  { en: "let alone", ja: "まして〜なんて" },
  { en: "on top of that", ja: "その上さらに" },
  { en: "as for", ja: "〜について言えば" },
  { en: "as if", ja: "まるで〜かのように" },
  { en: "in order to", ja: "〜するために" },
  { en: "be willing to", ja: "〜してもかまわないと思っている" },
  { en: "be bound to", ja: "きっと〜するはずだ" },
  { en: "be dying to", ja: "〜したくてたまらない" },
  { en: "be on the fence", ja: "どちらか決めかねている" },
  { en: "be broke", ja: "金欠である" },
  { en: "be starving", ja: "腹ぺこである" }
];
